package app.aaps.plugins.automation

import app.aaps.core.data.time.T
import app.aaps.core.interfaces.automation.AutomationEvent
import app.aaps.core.interfaces.automation.AutomationIconData
import app.aaps.core.interfaces.navigation.ElementType
import app.aaps.core.interfaces.logging.AAPSLogger
import app.aaps.core.interfaces.utils.DateUtil
import app.aaps.core.ui.compose.icons.IcUserOptions
import app.aaps.plugins.automation.actions.ActionFactory
import app.aaps.plugins.automation.actions.Action
import app.aaps.plugins.automation.actions.ActionDummy
import app.aaps.plugins.automation.actions.ActionStopProcessing
import app.aaps.plugins.automation.triggers.TriggerDeps
import app.aaps.plugins.automation.triggers.TriggerFactory
import app.aaps.plugins.automation.triggers.TriggerConnector
import app.aaps.plugins.automation.triggers.TriggerDummy
import org.json.JSONArray
import org.json.JSONObject
import java.util.UUID

class AutomationEventObject(private val factory: AutomationEventFactory) : AutomationEvent {

    private val aapsLogger: AAPSLogger get() = factory.aapsLogger
    private val actionFactory: ActionFactory get() = factory.actionFactory
    private val triggerFactory: TriggerFactory get() = factory.triggerFactory
    private val triggerDeps: TriggerDeps get() = factory.triggerDeps
    private val dateUtil: DateUtil get() = factory.dateUtil

    override var id: String = UUID.randomUUID().toString()
    override var title: String = ""
    override var isEnabled = true
    var systemAction: Boolean = false // true = generated by AAPS, false = entered by user
    var readOnly: Boolean = false // removing, editing disabled
    var autoRemove: Boolean = false // auto-remove once used
    override var userAction: Boolean = false // shows button on Overview

    var trigger: TriggerConnector = TriggerConnector(triggerDeps)
    val actions: MutableList<Action> = ArrayList()

    var lastRun: Long = 0

    override suspend fun canRun(): Boolean = trigger.shouldRun()
    override suspend fun preconditionCanRun(): Boolean = getPreconditions().shouldRun()
    override fun firstActionIcon(): AutomationIconData? =
        actions.firstOrNull()?.let { action ->
            AutomationIconData(action.composeIcon(), action.elementType())
        }

    override fun actionsDescription(): List<String> = actions.map { it.shortDescription() }

    override fun triggerIcons(): Set<AutomationIconData> {
        val icons = mutableSetOf<AutomationIconData>()
        if (userAction) icons.add(AutomationIconData(IcUserOptions))
        fillTriggerIconSet(trigger, icons)
        return icons
    }

    override fun actionIcons(): Set<AutomationIconData> =
        actions.mapTo(mutableSetOf()) { action ->
            AutomationIconData(action.composeIcon(), action.elementType())
        }

    private fun fillTriggerIconSet(connector: TriggerConnector, set: MutableSet<AutomationIconData>) {
        for (t in connector.list) {
            if (t is TriggerConnector) {
                fillTriggerIconSet(t, set)
            } else {
                set.add(AutomationIconData(t.composeIcon(), t.elementType()))
            }
        }
    }

    internal fun getPreconditions(): TriggerConnector {
        val trigger = TriggerConnector(triggerDeps, TriggerConnector.Type.AND)
        for (action in actions) {
            action.precondition?.let { trigger.list.add(it) }
        }
        return trigger
    }

    fun addAction(action: Action) = actions.add(action)

    fun areActionsValid(): Boolean {
        var result = true
        for (action in actions) result = result && action.isValid()
        if (!result) isEnabled = false
        return result
    }

    fun hasStopProcessing(): Boolean {
        for (action in actions) if (action is ActionStopProcessing) return true
        return false
    }

    fun toJSON(): String {
        val array = JSONArray()
        for (a in actions) array.put(a.toJSON())
        return JSONObject()
            .put("id", id)
            .put("title", title)
            .put("enabled", isEnabled)
            .put("systemAction", systemAction)
            .put("readOnly", readOnly)
            .put("autoRemove", autoRemove)
            .put("userAction", userAction)
            .put("trigger", trigger.toJSON())
            .put("actions", array)
            .toString()
    }

    fun fromJSON(data: String): AutomationEventObject {
        val d = JSONObject(data)
        id = d.optString("id", "").ifEmpty { UUID.randomUUID().toString() }
        title = d.optString("title", "")
        isEnabled = d.optBoolean("enabled", true)
        systemAction = d.optBoolean("systemAction", false)
        readOnly = d.optBoolean("readOnly", false)
        autoRemove = d.optBoolean("autoRemove", false)
        userAction = d.optBoolean("userAction", false)
        trigger = triggerFactory.instantiate(JSONObject(d.getString("trigger"))) as TriggerConnector
        val array = d.getJSONArray("actions")
        actions.clear()
        for (i in 0 until array.length()) {
            actionFactory.instantiate(JSONObject(array.getString(i)))?.let {
                actions.add(it)
            }
        }
        return this
    }

    fun shouldRun(): Boolean {
        return lastRun <= dateUtil.now() - T.mins(5).msecs()
    }
}
