package app.aaps.plugins.automation

import app.aaps.core.data.time.T
import app.aaps.core.interfaces.automation.AutomationEvent
import app.aaps.core.interfaces.logging.AAPSLogger
import app.aaps.core.interfaces.utils.DateUtil
import app.aaps.plugins.automation.actions.Action
import app.aaps.plugins.automation.actions.ActionDummy
import app.aaps.plugins.automation.actions.ActionStopProcessing
import app.aaps.plugins.automation.triggers.TriggerConnector
import app.aaps.plugins.automation.triggers.TriggerDummy
import dagger.android.HasAndroidInjector
import org.json.JSONArray
import org.json.JSONObject
import java.util.UUID
import javax.inject.Inject

class AutomationEventObject(private val injector: HasAndroidInjector) : AutomationEvent {

    @Inject lateinit var aapsLogger: AAPSLogger
    @Inject lateinit var dateUtil: DateUtil

    override var id: String = UUID.randomUUID().toString()
    override var title: String = ""
    override var isEnabled = true
    var systemAction: Boolean = false // true = generated by AAPS, false = entered by user
    var readOnly: Boolean = false // removing, editing disabled
    var autoRemove: Boolean = false // auto-remove once used
    var userAction: Boolean = false // shows button on Overview

    var trigger: TriggerConnector = TriggerConnector(injector)
    val actions: MutableList<Action> = ArrayList()

    var lastRun: Long = 0

    init {
        injector.androidInjector().inject(this)
    }

    override suspend fun canRun(): Boolean = trigger.shouldRun()
    override suspend fun preconditionCanRun(): Boolean = getPreconditions().shouldRun()
    override fun firstActionIcon(): Int? = actions.firstOrNull()?.icon()
    override fun actionsDescription(): List<String> = actions.map { it.shortDescription() }

    override fun triggerIcons(): Set<Int> {
        val icons = mutableSetOf<Int>()
        if (userAction) icons.add(app.aaps.core.ui.R.drawable.ic_user_options)
        fillTriggerIconSet(trigger, icons)
        return icons
    }

    override fun actionIcons(): Set<Int> = actions.mapTo(mutableSetOf()) { it.icon() }

    private fun fillTriggerIconSet(connector: TriggerConnector, set: MutableSet<Int>) {
        for (t in connector.list) {
            if (t is TriggerConnector) {
                fillTriggerIconSet(t, set)
            } else {
                val icon = t.icon()
                if (icon.isPresent) {
                    set.add(icon.get())
                }
            }
        }
    }

    internal fun getPreconditions(): TriggerConnector {
        val trigger = TriggerConnector(injector, TriggerConnector.Type.AND)
        for (action in actions) {
            action.precondition?.let { trigger.list.add(it) }
        }
        return trigger
    }

    fun addAction(action: Action) = actions.add(action)

    fun areActionsValid(): Boolean {
        var result = true
        for (action in actions) result = result && action.isValid()
        if (!result) isEnabled = false
        return result
    }

    fun hasStopProcessing(): Boolean {
        for (action in actions) if (action is ActionStopProcessing) return true
        return false
    }

    fun toJSON(): String {
        val array = JSONArray()
        for (a in actions) array.put(a.toJSON())
        return JSONObject()
            .put("id", id)
            .put("title", title)
            .put("enabled", isEnabled)
            .put("systemAction", systemAction)
            .put("readOnly", readOnly)
            .put("autoRemove", autoRemove)
            .put("userAction", userAction)
            .put("trigger", trigger.toJSON())
            .put("actions", array)
            .toString()
    }

    fun fromJSON(data: String): AutomationEventObject {
        val d = JSONObject(data)
        id = d.optString("id", "").ifEmpty { UUID.randomUUID().toString() }
        title = d.optString("title", "")
        isEnabled = d.optBoolean("enabled", true)
        systemAction = d.optBoolean("systemAction", false)
        readOnly = d.optBoolean("readOnly", false)
        autoRemove = d.optBoolean("autoRemove", false)
        userAction = d.optBoolean("userAction", false)
        trigger = TriggerDummy(injector).instantiate(JSONObject(d.getString("trigger"))) as TriggerConnector
        val array = d.getJSONArray("actions")
        actions.clear()
        for (i in 0 until array.length()) {
            ActionDummy(injector).instantiate(JSONObject(array.getString(i)))?.let {
                actions.add(it)
            }
        }
        return this
    }

    fun shouldRun(): Boolean {
        return lastRun <= dateUtil.now() - T.mins(5).msecs()
    }
}
