package app.aaps.plugins.automation

import app.aaps.core.data.time.T
import app.aaps.core.interfaces.automation.AutomationEvent
import app.aaps.core.interfaces.automation.AutomationIconData
import app.aaps.core.interfaces.navigation.ElementType
import app.aaps.core.interfaces.logging.AAPSLogger
import app.aaps.core.interfaces.utils.DateUtil
import app.aaps.core.ui.compose.icons.IcUserOptions
import app.aaps.plugins.automation.actions.ActionFactory
import app.aaps.plugins.automation.actions.Action
import app.aaps.plugins.automation.actions.ActionDummy
import app.aaps.plugins.automation.actions.ActionStopProcessing
import app.aaps.plugins.automation.triggers.TriggerDeps
import app.aaps.plugins.automation.triggers.TriggerFactory
import app.aaps.plugins.automation.triggers.TriggerConnector
import app.aaps.plugins.automation.triggers.TriggerDummy
import app.aaps.core.utils.lenientBoolean
import app.aaps.core.utils.lenientString
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.put
import java.util.UUID

class AutomationEventObject(private val factory: AutomationEventFactory) : AutomationEvent {

    private val aapsLogger: AAPSLogger get() = factory.aapsLogger
    private val actionFactory: ActionFactory get() = factory.actionFactory
    private val triggerFactory: TriggerFactory get() = factory.triggerFactory
    private val triggerDeps: TriggerDeps get() = factory.triggerDeps
    private val dateUtil: DateUtil get() = factory.dateUtil

    override var id: String = UUID.randomUUID().toString()
    override var title: String = ""
    override var isEnabled = true
    var systemAction: Boolean = false // true = generated by AAPS, false = entered by user
    var readOnly: Boolean = false // removing, editing disabled
    var autoRemove: Boolean = false // auto-remove once used
    override var userAction: Boolean = false // shows button on Overview

    var trigger: TriggerConnector = TriggerConnector(triggerDeps)
    val actions: MutableList<Action> = ArrayList()

    var lastRun: Long = 0

    override suspend fun canRun(): Boolean = trigger.shouldRun()
    override suspend fun preconditionCanRun(): Boolean = getPreconditions().shouldRun()
    override fun firstActionIcon(): AutomationIconData? =
        actions.firstOrNull()?.let { action ->
            AutomationIconData(action.composeIcon(), action.elementType())
        }

    override fun actionsDescription(): List<String> = actions.map { it.shortDescription() }

    override fun triggerIcons(): Set<AutomationIconData> {
        val icons = mutableSetOf<AutomationIconData>()
        if (userAction) icons.add(AutomationIconData(IcUserOptions))
        fillTriggerIconSet(trigger, icons)
        return icons
    }

    override fun actionIcons(): Set<AutomationIconData> =
        actions.mapTo(mutableSetOf()) { action ->
            AutomationIconData(action.composeIcon(), action.elementType())
        }

    private fun fillTriggerIconSet(connector: TriggerConnector, set: MutableSet<AutomationIconData>) {
        for (t in connector.list) {
            if (t is TriggerConnector) {
                fillTriggerIconSet(t, set)
            } else {
                set.add(AutomationIconData(t.composeIcon(), t.elementType()))
            }
        }
    }

    internal fun getPreconditions(): TriggerConnector {
        val trigger = TriggerConnector(triggerDeps, TriggerConnector.Type.AND)
        for (action in actions) {
            action.precondition?.let { trigger.list.add(it) }
        }
        return trigger
    }

    fun addAction(action: Action) = actions.add(action)

    fun areActionsValid(): Boolean {
        var result = true
        for (action in actions) result = result && action.isValid()
        if (!result) isEnabled = false
        return result
    }

    fun hasStopProcessing(): Boolean {
        for (action in actions) if (action is ActionStopProcessing) return true
        return false
    }

    // The trigger and each action are stored as JSON *strings*, not nested objects. That is the format
    // every existing install has on disk and in sync, so it stays.
    fun toJSON(): String =
        buildJsonObject {
            put("id", id)
            put("title", title)
            put("enabled", isEnabled)
            put("systemAction", systemAction)
            put("readOnly", readOnly)
            put("autoRemove", autoRemove)
            put("userAction", userAction)
            put("trigger", trigger.toJSON())
            put("actions", buildJsonArray { for (a in actions) add(JsonPrimitive(a.toJSON())) })
        }.toString()

    fun fromJSON(data: String): AutomationEventObject {
        val d = jsonOf(data)
        id = d.lenientString("id", "").ifEmpty { UUID.randomUUID().toString() }
        title = d.lenientString("title", "")
        isEnabled = d.lenientBoolean("enabled", true)
        systemAction = d.lenientBoolean("systemAction", false)
        readOnly = d.lenientBoolean("readOnly", false)
        autoRemove = d.lenientBoolean("autoRemove", false)
        userAction = d.lenientBoolean("userAction", false)
        trigger = triggerFactory.instantiate(jsonOf(d.lenientString("trigger", "{}"))) as TriggerConnector
        val array = d["actions"] as? JsonArray ?: JsonArray(emptyList())
        actions.clear()
        for (element in array) {
            val child = (element as? JsonPrimitive)?.content ?: continue
            actionFactory.instantiate(jsonOf(child))?.let {
                actions.add(it)
            }
        }
        return this
    }

    private fun jsonOf(data: String): JsonObject =
        runCatching { Json.parseToJsonElement(data).jsonObject }.getOrElse { JsonObject(emptyMap()) }

    fun shouldRun(): Boolean {
        return lastRun <= dateUtil.now() - T.mins(5).msecs()
    }
}
