package app.aaps.plugins.sync.xdrip.extensions

import app.aaps.core.data.model.TB
import app.aaps.core.data.model.TE
import app.aaps.core.data.time.T
import app.aaps.core.interfaces.profile.Profile
import app.aaps.core.interfaces.utils.DateUtil
import app.aaps.core.objects.extensions.convertedToAbsolute
import org.json.JSONObject

fun TB.toJson(isAdd: Boolean, profile: Profile?, dateUtil: DateUtil): JSONObject? =
    profile?.let {
        JSONObject()
            .put("created_at", dateUtil.toISOString(timestamp))
            .put("enteredBy", "openaps://" + "AndroidAPS")
            .put("eventType", TE.Type.TEMPORARY_BASAL.text)
            .put("isValid", isValid)
            .put("duration", T.msecs(duration).mins())
            .put("durationInMilliseconds", duration) // rounded duration leads to different basal IOB
            .put("type", type.name)
            .put("rate", convertedToAbsolute(timestamp, profile)) // generated by OpenAPS, for compatibility
            .also {
                if (isAbsolute) it.put("absolute", rate)
                else it.put("percent", rate - 100)
                if (ids.pumpId != null) it.put("pumpId", ids.pumpId)
                if (ids.endId != null) it.put("endId", ids.endId)
                if (ids.pumpType != null) it.put("pumpType", ids.pumpType!!.name)
                if (ids.pumpSerial != null) it.put("pumpSerial", ids.pumpSerial)
                if (isAdd && ids.nightscoutId != null) it.put("_id", ids.nightscoutId)
            }
    }
