# These are supported funding model platforms
ko_fi: diabetesone
custom:
  - "https://www.nightscoutfoundation.org/donate"
  - "https://www.blockchain.com/explorer/addresses/btc/3KawK8aQe48478s6fxJ8Ms6VTWkwjgr9f2"
