package app.aaps.pump.medtrum.code

enum class PatchStep {
    START_DEACTIVATION,
    DEACTIVATE,
    FORCE_DEACTIVATION,
    DEACTIVATION_COMPLETE,
    PREPARE_PATCH,
    PREPARE_PATCH_CONNECT,
    PRIME,
    PRIMING,
    PRIME_COMPLETE,
    ATTACH_PATCH,
    ACTIVATE,
    ACTIVATE_COMPLETE,
    RETRY_ACTIVATION,
    RETRY_ACTIVATION_CONNECT,
    CANCEL,
    COMPLETE;
}
