package app.aaps.plugins.sync.nsclient.extensions

import app.aaps.core.data.model.TB
import app.aaps.core.data.model.TE
import app.aaps.core.data.pump.defs.PumpType
import app.aaps.core.data.time.T
import app.aaps.core.interfaces.profile.Profile
import app.aaps.core.interfaces.utils.DateUtil
import app.aaps.core.objects.extensions.convertedToAbsolute
import app.aaps.core.utils.JsonHelper
import org.json.JSONObject

fun TB.toJson(isAdd: Boolean, profile: Profile?, dateUtil: DateUtil): JSONObject? =
    profile?.let {
        JSONObject()
            .put("created_at", dateUtil.toISOString(timestamp))
            .put("enteredBy", "openaps://" + "AndroidAPS")
            .put("eventType", TE.Type.TEMPORARY_BASAL.text)
            .put("isValid", isValid)
            .put("duration", T.msecs(duration).mins())
            .put("durationInMilliseconds", duration) // rounded duration leads to different basal IOB
            .put("type", type.name)
            .put("rate", convertedToAbsolute(timestamp, profile)) // generated by OpenAPS, for compatibility
            .also {
                if (isAbsolute) it.put("absolute", rate)
                else it.put("percent", rate - 100)
                if (ids.pumpId != null) it.put("pumpId", ids.pumpId)
                if (ids.endId != null) it.put("endId", ids.endId)
                if (ids.pumpType != null) it.put("pumpType", ids.pumpType!!.name)
                if (ids.pumpSerial != null) it.put("pumpSerial", ids.pumpSerial)
                if (isAdd && ids.nightscoutId != null) it.put("_id", ids.nightscoutId)
            }
    }

fun TB.Companion.temporaryBasalFromJson(jsonObject: JSONObject): TB? {
    val timestamp =
        JsonHelper.safeGetLongAllowNull(jsonObject, "mills", null)
            ?: JsonHelper.safeGetLongAllowNull(jsonObject, "date", null)
            ?: return null
    val percent = JsonHelper.safeGetDoubleAllowNull(jsonObject, "percent")
    val absolute = JsonHelper.safeGetDoubleAllowNull(jsonObject, "absolute")
    val duration = JsonHelper.safeGetLongAllowNull(jsonObject, "duration") ?: return null
    val durationInMilliseconds = JsonHelper.safeGetLongAllowNull(jsonObject, "durationInMilliseconds")
    val type = TB.Type.fromString(JsonHelper.safeGetString(jsonObject, "type"))
    val isValid = JsonHelper.safeGetBoolean(jsonObject, "isValid", true)
    val id = JsonHelper.safeGetStringAllowNull(jsonObject, "identifier", null)
        ?: JsonHelper.safeGetStringAllowNull(jsonObject, "_id", null)
        ?: return null
    val pumpId = JsonHelper.safeGetLongAllowNull(jsonObject, "pumpId", null)
    val endPumpId = JsonHelper.safeGetLongAllowNull(jsonObject, "endId", null)
    val pumpType = PumpType.fromString(JsonHelper.safeGetStringAllowNull(jsonObject, "pumpType", null))
    val pumpSerial = JsonHelper.safeGetStringAllowNull(jsonObject, "pumpSerial", null)

    val rate: Double
    val isAbsolute: Boolean
    if (absolute != null) {
        rate = absolute
        isAbsolute = true
    } else if (percent != null) {
        rate = percent + 100
        isAbsolute = false
    } else return null
    if (duration == 0L && durationInMilliseconds == null) return null
    if (timestamp == 0L) return null

    return TB(
        timestamp = timestamp,
        rate = rate,
        duration = durationInMilliseconds ?: T.mins(duration).msecs(),
        type = type,
        isAbsolute = isAbsolute,
        isValid = isValid
    ).also {
        it.ids.nightscoutId = id
        it.ids.pumpId = pumpId
        it.ids.endId = endPumpId
        it.ids.pumpType = pumpType
        it.ids.pumpSerial = pumpSerial
    }
}