plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.ksp)
    alias(libs.plugins.compose.compiler)
    // Metro beside Dagger in the same ordinary Android library module. This module is not
    // multiplatform and never will be, so Metro is here only to take over the Android entry points
    // Hilt answers today - the precondition for removing Dagger at all.
    alias(libs.plugins.metro)
    id("android-module-dependencies")
    id("all-open-dependencies")
    id("test-module-dependencies")
    id("compose-test-module-dependencies")
    id("jacoco-module-dependencies")
}

android {
    namespace = "app.aaps.implementation"

    buildFeatures {
        compose = true
    }
}

dependencies {
    implementation(project(":core:data"))
    implementation(project(":core:interfaces"))
    implementation(libs.kotlinx.datetime)
    implementation(project(":core:keys"))
    implementation(project(":core:objects"))
    implementation(project(":core:ui"))
    implementation(project(":core:utils"))
    implementation(project(":shared:impl"))
    implementation(libs.com.squareup.okhttp3.okhttp)

    testImplementation(project(":shared:tests"))
    testImplementation(project(":plugins:aps"))
    testImplementation(project(":pump:virtual"))
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.androidx.work.testing)

    api(libs.androidx.datastore.preferences)
    // Protection
    implementation(libs.androidx.biometric)
    //Logger
    implementation(libs.org.slf4j.api)
    implementation(libs.com.github.tony19.logback.android)

    // Compose
    api(platform(libs.androidx.compose.bom))
    api(libs.androidx.compose.runtime)

    ksp(libs.com.google.dagger.compiler)
    ksp(libs.com.google.dagger.hilt.compiler)
    ksp(libs.com.google.dagger.android.processor)
    // Hilt WorkManager integration for @HiltWorker workers (factory glue generated by androidx hilt-compiler)
    implementation(libs.androidx.hilt.work)
    ksp(libs.androidx.hilt.compiler)
}