package info.nightscout.androidaps.database.entities

import androidx.room.Entity
import androidx.room.PrimaryKey
import com.google.gson.annotations.SerializedName
import info.nightscout.androidaps.database.R
import info.nightscout.androidaps.database.TABLE_USER_ENTRY
import info.nightscout.androidaps.database.interfaces.DBEntry
import info.nightscout.androidaps.database.interfaces.DBEntryWithTime
import java.util.*

@Entity(tableName = TABLE_USER_ENTRY)
data class UserEntry(
    @PrimaryKey(autoGenerate = true)
    override var id: Long = 0L,
    override var timestamp: Long,
    override var utcOffset: Long = TimeZone.getDefault().getOffset(timestamp).toLong(),
    var action: Action,
    var s: String,
    var d1: Double,
    var d2: Double,
    var i1: Int,
    var i2: Int
) : DBEntry, DBEntryWithTime {
    enum class Action (val stringId:Int) {
        @SerializedName("BOLUS") BOLUS (R.string.uel_bolus),
        @SerializedName("BOLUS_WIZARD") BOLUS_WIZARD (R.string.uel_bolus_wizard),
        @SerializedName("BOLUS_ADVISOR") BOLUS_ADVISOR (R.string.uel_bolus_advisor),
        @SerializedName("BOLUS_RECORD") BOLUS_RECORD (R.string.uel_bolus_record),
        @SerializedName("EXTENDED_BOLUS") EXTENDED_BOLUS (R.string.uel_extended_bolus),
        @SerializedName("SUPERBOLUS_TBR") SUPERBOLUS_TBR (R.string.uel_superbolus_tbr),
        @SerializedName("CARBS") CARBS (R.string.uel_carbs),
        @SerializedName("EXTENDED_CARBS") EXTENDED_CARBS (R.string.uel_extended_carbs),
        @SerializedName("TEMP_BASAL") TEMP_BASAL (R.string.uel_temp_basal),
        @SerializedName("TT") TT (R.string.uel_tt),
        @SerializedName("TT_ACTIVITY") TT_ACTIVITY (R.string.uel_tt_activity),
        @SerializedName("TT_EATING_SOON") TT_EATING_SOON (R.string.uel_tt_eating_soon),
        @SerializedName("TT_HYPO") TT_HYPO (R.string.uel_tt_hypo),
        @SerializedName("NEW_PROFILE") NEW_PROFILE (R.string.uel_new_profile),
        @SerializedName("CLONE_PROFILE") CLONE_PROFILE (R.string.uel_clone_profile),
        @SerializedName("STORE_PROFILE") STORE_PROFILE (R.string.uel_store_profile),
        @SerializedName("PROFILE_SWITCH") PROFILE_SWITCH (R.string.uel_profile_switch),
        @SerializedName("PROFILE_SWITCH_CLONED") PROFILE_SWITCH_CLONED (R.string.uel_profile_switch_cloned),
        @SerializedName("CLOSED_LOOP_MODE") CLOSED_LOOP_MODE (R.string.uel_closed_loop_mode),
        @SerializedName("LGS_LOOP_MODE") LGS_LOOP_MODE (R.string.uel_lgs_loop_mode),
        @SerializedName("OPEN_LOOP_MODE") OPEN_LOOP_MODE (R.string.uel_open_loop_mode),
        @SerializedName("LOOP_DISABLED") LOOP_DISABLED (R.string.uel_loop_disabled),
        @SerializedName("LOOP_ENABLED") LOOP_ENABLED (R.string.uel_loop_enabled),
        @SerializedName("RECONNECT") RECONNECT (R.string.uel_reconnect),
        @SerializedName("DISCONNECT_15M") DISCONNECT_15M (R.string.uel_disconnect_15m),
        @SerializedName("DISCONNECT_30M") DISCONNECT_30M (R.string.uel_disconnect_30m),
        @SerializedName("DISCONNECT_1H") DISCONNECT_1H (R.string.uel_disconnect_1h),
        @SerializedName("DISCONNECT_2H") DISCONNECT_2H (R.string.uel_disconnect_2h),
        @SerializedName("DISCONNECT_3H") DISCONNECT_3H (R.string.uel_disconnect_3h),
        @SerializedName("RESUME") RESUME (R.string.uel_resume),
        @SerializedName("SUSPEND_1H") SUSPEND_1H (R.string.uel_suspend_1h),
        @SerializedName("SUSPEND_2H") SUSPEND_2H (R.string.uel_suspend_2h),
        @SerializedName("SUSPEND_3H") SUSPEND_3H (R.string.uel_suspend_3h),
        @SerializedName("SUSPEND_10H") SUSPEND_10H (R.string.uel_suspend_10h),
        @SerializedName("HW_PUMP_ALLOWED") HW_PUMP_ALLOWED (R.string.uel_hw_pump_allowed),
        @SerializedName("CLEAR_PAIRING_KEYS") CLEAR_PAIRING_KEYS (R.string.uel_clear_pairing_keys),
        @SerializedName("ACCEPTS_TEMP_BASAL") ACCEPTS_TEMP_BASAL (R.string.uel_accepts_temp_basal),
        @SerializedName("CANCEL_TEMP_BASAL") CANCEL_TEMP_BASAL (R.string.uel_cancel_temp_basal),
        @SerializedName("CANCEL_EXTENDED_BOLUS") CANCEL_EXTENDED_BOLUS (R.string.uel_cancel_extended_bolus),
        @SerializedName("CANCEL_TT") CANCEL_TT (R.string.uel_cancel_tt),
        @SerializedName("CAREPORTAL") CAREPORTAL (R.string.uel_careportal),
        @SerializedName("CALIBRATION") CALIBRATION (R.string.uel_calibration),
        @SerializedName("INSULIN_CHANGE") INSULIN_CHANGE (R.string.uel_insulin_change),
        @SerializedName("PRIME_BOLUS") PRIME_BOLUS (R.string.uel_prime_bolus),
        @SerializedName("SITE_CHANGE") SITE_CHANGE (R.string.uel_site_change),
        @SerializedName("TREATMENT") TREATMENT (R.string.uel_treatment),
        @SerializedName("CAREPORTAL_NS_REFRESH") CAREPORTAL_NS_REFRESH (R.string.uel_careportal_ns_refresh),
        @SerializedName("PROFILE_SWITCH_NS_REFRESH") PROFILE_SWITCH_NS_REFRESH (R.string.uel_profile_switch_ns_refresh),
        @SerializedName("TREATMENTS_NS_REFRESH") TREATMENTS_NS_REFRESH (R.string.uel_treatments_ns_refresh),
        @SerializedName("TT_NS_REFRESH") TT_NS_REFRESH (R.string.uel_tt_ns_refresh),
        @SerializedName("AUTOMATION_REMOVED") AUTOMATION_REMOVED (R.string.uel_automation_removed),
        @SerializedName("BG_REMOVED") BG_REMOVED (R.string.uel_bg_removed),
        @SerializedName("CAREPORTAL_REMOVED") CAREPORTAL_REMOVED (R.string.uel_careportal_removed),
        @SerializedName("EXTENDED_BOLUS_REMOVED") EXTENDED_BOLUS_REMOVED (R.string.uel_extended_bolus_removed),
        @SerializedName("FOOD_REMOVED") FOOD_REMOVED (R.string.uel_food_removed),
        @SerializedName("PROFILE_REMOVED") PROFILE_REMOVED (R.string.uel_profile_removed),
        @SerializedName("PROFILE_SWITCH_REMOVED") PROFILE_SWITCH_REMOVED (R.string.uel_profile_switch_removed),
        @SerializedName("RESTART_EVENTS_REMOVED") RESTART_EVENTS_REMOVED (R.string.uel_restart_events_removed),
        @SerializedName("TREATMENT_REMOVED") TREATMENT_REMOVED (R.string.uel_treatment_removed),
        @SerializedName("TT_REMOVED") TT_REMOVED (R.string.uel_tt_removed),
        @SerializedName("NS_PAUSED") NS_PAUSED (R.string.uel_ns_paused),
        @SerializedName("NS_QUEUE_CLEARED") NS_QUEUE_CLEARED (R.string.uel_ns_queue_cleared),
        @SerializedName("NS_SETTINGS_COPIED") NS_SETTINGS_COPIED (R.string.uel_ns_settings_copied),
        @SerializedName("ERROR_DIALOG_OK") ERROR_DIALOG_OK (R.string.uel_error_dialog_ok),
        @SerializedName("ERROR_DIALOG_MUTE") ERROR_DIALOG_MUTE (R.string.uel_error_dialog_mute),
        @SerializedName("ERROR_DIALOG_MUTE_5MIN") ERROR_DIALOG_MUTE_5MIN (R.string.uel_error_dialog_mute_5min),
        @SerializedName("OBJECTIVE_STARTED") OBJECTIVE_STARTED (R.string.uel_objective_started),
        @SerializedName("OBJECTIVE_UNSTARTED") OBJECTIVE_UNSTARTED (R.string.uel_objective_unstarted),
        @SerializedName("OBJECTIVES_SKIPPED") OBJECTIVES_SKIPPED (R.string.uel_objectives_skipped),
        @SerializedName("STAT_RESET") STAT_RESET (R.string.uel_stat_reset),
        @SerializedName("DELETE_LOGS") DELETE_LOGS (R.string.uel_delete_logs),
        @SerializedName("DELETE_FUTURE_TREATMENTS") DELETE_FUTURE_TREATMENTS (R.string.uel_delete_future_treatments),
        @SerializedName("EXPORT_SETTINGS") EXPORT_SETTINGS (R.string.uel_export_settings),
        @SerializedName("IMPORT_SETTINGS") IMPORT_SETTINGS (R.string.uel_import_settings),
        @SerializedName("RESET_DATABASES") RESET_DATABASES (R.string.uel_reset_databases),
        @SerializedName("EXPORT_DATABASES") EXPORT_DATABASES (R.string.uel_export_databases),
        @SerializedName("IMPORT_DATABASES") IMPORT_DATABASES (R.string.uel_import_databases),
        @SerializedName("OTP_EXPORT") OTP_EXPORT (R.string.uel_otp_export),
        @SerializedName("OTP_RESET") OTP_RESET (R.string.uel_otp_reset),
        @SerializedName("SMS_BASAL") SMS_BASAL (R.string.uel_sms_basal),
        @SerializedName("SMS_BOLUS") SMS_BOLUS (R.string.uel_sms_bolus),
        @SerializedName("SMS_CAL") SMS_CAL (R.string.uel_sms_cal),
        @SerializedName("SMS_CARBS") SMS_CARBS (R.string.uel_sms_carbs),
        @SerializedName("SMS_EXTENDED_BOLUS") SMS_EXTENDED_BOLUS (R.string.uel_sms_extended_bolus),
        @SerializedName("SMS_LOOP_DISABLED") SMS_LOOP_DISABLED (R.string.uel_sms_loop_disabled),
        @SerializedName("SMS_LOOP_ENABLED") SMS_LOOP_ENABLED (R.string.uel_sms_loop_enabled),
        @SerializedName("SMS_LOOP_RESUME") SMS_LOOP_RESUME (R.string.uel_sms_loop_resume),
        @SerializedName("SMS_LOOP_SUSPEND") SMS_LOOP_SUSPEND (R.string.uel_sms_loop_suspend),
        @SerializedName("SMS_PROFILE") SMS_PROFILE (R.string.uel_sms_profile),
        @SerializedName("SMS_PUMP_CONNECT") SMS_PUMP_CONNECT (R.string.uel_sms_pump_connect),
        @SerializedName("SMS_PUMP_DISCONNECT") SMS_PUMP_DISCONNECT (R.string.uel_sms_pump_disconnect),
        @SerializedName("SMS_SMS") SMS_SMS (R.string.uel_sms_sms),
        @SerializedName("SMS_TT") SMS_TT (R.string.uel_sms_tt),

    }
}