package info.nightscout.androidaps.utils

import info.nightscout.androidaps.core.R
import info.nightscout.androidaps.database.entities.TemporaryTarget
import info.nightscout.androidaps.database.entities.TherapyEvent
import info.nightscout.androidaps.database.entities.UserEntry.*
import info.nightscout.androidaps.utils.resources.ResourceHelper
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class Translator @Inject internal constructor(
    private val resourceHelper: ResourceHelper
) {

    fun translate(text: String): String =
        when (text) {
            TherapyEvent.Type.FINGER_STICK_BG_VALUE.text   -> resourceHelper.gs(R.string.careportal_bgcheck)
            TherapyEvent.Type.SNACK_BOLUS.text             -> resourceHelper.gs(R.string.careportal_snackbolus)
            TherapyEvent.Type.MEAL_BOLUS.text              -> resourceHelper.gs(R.string.careportal_mealbolus)
            TherapyEvent.Type.CORRECTION_BOLUS.text        -> resourceHelper.gs(R.string.careportal_correctionbolus)
            TherapyEvent.Type.CARBS_CORRECTION.text        -> resourceHelper.gs(R.string.careportal_carbscorrection)
            TherapyEvent.Type.BOLUS_WIZARD.text            -> resourceHelper.gs(R.string.boluswizard)
            TherapyEvent.Type.COMBO_BOLUS.text             -> resourceHelper.gs(R.string.careportal_combobolus)
            TherapyEvent.Type.ANNOUNCEMENT.text            -> resourceHelper.gs(R.string.careportal_announcement)
            TherapyEvent.Type.NOTE.text                    -> resourceHelper.gs(R.string.careportal_note)
            TherapyEvent.Type.QUESTION.text                -> resourceHelper.gs(R.string.careportal_question)
            TherapyEvent.Type.EXERCISE.text                -> resourceHelper.gs(R.string.careportal_exercise)
            TherapyEvent.Type.CANNULA_CHANGE.text          -> resourceHelper.gs(R.string.careportal_pumpsitechange)
            TherapyEvent.Type.PUMP_BATTERY_CHANGE.text     -> resourceHelper.gs(R.string.careportal_pumpbatterychange)
            TherapyEvent.Type.SENSOR_STARTED.text          -> resourceHelper.gs(R.string.careportal_cgmsensorstart)
            TherapyEvent.Type.SENSOR_STOPPED.text          -> resourceHelper.gs(R.string.careportal_cgm_sensor_stop)
            TherapyEvent.Type.SENSOR_CHANGE.text           -> resourceHelper.gs(R.string.careportal_cgmsensorinsert)
            TherapyEvent.Type.INSULIN_CHANGE.text          -> resourceHelper.gs(R.string.careportal_insulincartridgechange)
            TherapyEvent.Type.DAD_ALERT.text               -> resourceHelper.gs(R.string.careportal_dad_alert)
            TherapyEvent.Type.TEMPORARY_BASAL_START.text   -> resourceHelper.gs(R.string.careportal_tempbasalstart)
            TherapyEvent.Type.TEMPORARY_BASAL_END.text     -> resourceHelper.gs(R.string.careportal_tempbasalend)
            TherapyEvent.Type.PROFILE_SWITCH.text          -> resourceHelper.gs(R.string.careportal_profileswitch)
            TherapyEvent.Type.TEMPORARY_TARGET.text        -> resourceHelper.gs(R.string.careportal_temporarytarget)
            TherapyEvent.Type.TEMPORARY_TARGET_CANCEL.text -> resourceHelper.gs(R.string.careportal_temporarytargetcancel)
            TherapyEvent.Type.APS_OFFLINE.text             -> resourceHelper.gs(R.string.careportal_openapsoffline)
            TherapyEvent.Type.NS_MBG.text                  -> resourceHelper.gs(R.string.careportal_mbg)
            TherapyEvent.MeterType.FINGER.text             -> resourceHelper.gs(R.string.glucosetype_finger)
            TherapyEvent.MeterType.SENSOR.text             -> resourceHelper.gs(R.string.glucosetype_sensor)
            TherapyEvent.MeterType.MANUAL.text             -> resourceHelper.gs(R.string.manual)

            TemporaryTarget.Reason.CUSTOM.text             -> resourceHelper.gs(R.string.custom)
            TemporaryTarget.Reason.HYPOGLYCEMIA.text       -> resourceHelper.gs(R.string.hypo)
            TemporaryTarget.Reason.EATING_SOON.text        -> resourceHelper.gs(R.string.eatingsoon)
            TemporaryTarget.Reason.ACTIVITY.text           -> resourceHelper.gs(R.string.activity)
            TemporaryTarget.Reason.AUTOMATION.text         -> resourceHelper.gs(R.string.automation)
            TemporaryTarget.Reason.WEAR.text               -> resourceHelper.gs(R.string.wear)

            Action.BOLUS.name                               -> resourceHelper.gs(R.string.uel_bolus)
            Action.BOLUS_ADVISOR.name                       -> resourceHelper.gs(R.string.uel_bolus_advisor)
            Action.BOLUS_RECORD.name                        -> resourceHelper.gs(R.string.uel_bolus_record)
            Action.EXTENDED_BOLUS.name                      -> resourceHelper.gs(R.string.uel_extended_bolus)
            Action.SUPERBOLUS_TBR.name                      -> resourceHelper.gs(R.string.uel_superbolus_tbr)
            Action.CARBS.name                               -> resourceHelper.gs(R.string.uel_carbs)
            Action.EXTENDED_CARBS.name                      -> resourceHelper.gs(R.string.uel_extended_carbs)
            Action.TEMP_BASAL.name                          -> resourceHelper.gs(R.string.uel_temp_basal)
            Action.TT.name                                  -> resourceHelper.gs(R.string.uel_tt)
            Action.NEW_PROFILE.name                         -> resourceHelper.gs(R.string.uel_new_profile)
            Action.CLONE_PROFILE.name                       -> resourceHelper.gs(R.string.uel_clone_profile)
            Action.STORE_PROFILE.name                       -> resourceHelper.gs(R.string.uel_store_profile)
            Action.PROFILE_SWITCH.name                      -> resourceHelper.gs(R.string.uel_profile_switch)
            Action.PROFILE_SWITCH_CLONED.name               -> resourceHelper.gs(R.string.uel_profile_switch_cloned)
            Action.CLOSED_LOOP_MODE.name                    -> resourceHelper.gs(R.string.uel_closed_loop_mode)
            Action.LGS_LOOP_MODE.name                       -> resourceHelper.gs(R.string.uel_lgs_loop_mode)
            Action.OPEN_LOOP_MODE.name                      -> resourceHelper.gs(R.string.uel_open_loop_mode)
            Action.LOOP_DISABLED.name                       -> resourceHelper.gs(R.string.uel_loop_disabled)
            Action.LOOP_ENABLED.name                        -> resourceHelper.gs(R.string.uel_loop_enabled)
            Action.RECONNECT.name                           -> resourceHelper.gs(R.string.uel_reconnect)
            Action.DISCONNECT.name                          -> resourceHelper.gs(R.string.uel_disconnect)
            Action.RESUME.name                              -> resourceHelper.gs(R.string.uel_resume)
            Action.SUSPEND.name                             -> resourceHelper.gs(R.string.uel_suspend)
            Action.HW_PUMP_ALLOWED.name                     -> resourceHelper.gs(R.string.uel_hw_pump_allowed)
            Action.CLEAR_PAIRING_KEYS.name                  -> resourceHelper.gs(R.string.uel_clear_pairing_keys)
            Action.ACCEPTS_TEMP_BASAL.name                  -> resourceHelper.gs(R.string.uel_accepts_temp_basal)
            Action.CANCEL_TEMP_BASAL.name                   -> resourceHelper.gs(R.string.uel_cancel_temp_basal)
            Action.CANCEL_EXTENDED_BOLUS.name               -> resourceHelper.gs(R.string.uel_cancel_extended_bolus)
            Action.CANCEL_TT.name                           -> resourceHelper.gs(R.string.uel_cancel_tt)
            Action.CAREPORTAL.name                          -> resourceHelper.gs(R.string.uel_careportal)
            Action.CALIBRATION.name                         -> resourceHelper.gs(R.string.uel_calibration)
            Action.PRIME_BOLUS.name                         -> resourceHelper.gs(R.string.uel_prime_bolus)
            Action.TREATMENT.name                           -> resourceHelper.gs(R.string.uel_treatment)
            Action.CAREPORTAL_NS_REFRESH.name               -> resourceHelper.gs(R.string.uel_careportal_ns_refresh)
            Action.PROFILE_SWITCH_NS_REFRESH.name           -> resourceHelper.gs(R.string.uel_profile_switch_ns_refresh)
            Action.TREATMENTS_NS_REFRESH.name               -> resourceHelper.gs(R.string.uel_treatments_ns_refresh)
            Action.TT_NS_REFRESH.name                       -> resourceHelper.gs(R.string.uel_tt_ns_refresh)
            Action.AUTOMATION_REMOVED.name                  -> resourceHelper.gs(R.string.uel_automation_removed)
            Action.BG_REMOVED.name                          -> resourceHelper.gs(R.string.uel_bg_removed)
            Action.CAREPORTAL_REMOVED.name                  -> resourceHelper.gs(R.string.uel_careportal_removed)
            Action.EXTENDED_BOLUS_REMOVED.name              -> resourceHelper.gs(R.string.uel_extended_bolus_removed)
            Action.FOOD_REMOVED.name                        -> resourceHelper.gs(R.string.uel_food_removed)
            Action.PROFILE_REMOVED.name                     -> resourceHelper.gs(R.string.uel_profile_removed)
            Action.PROFILE_SWITCH_REMOVED.name              -> resourceHelper.gs(R.string.uel_profile_switch_removed)
            Action.RESTART_EVENTS_REMOVED.name              -> resourceHelper.gs(R.string.uel_restart_events_removed)
            Action.TREATMENT_REMOVED.name                   -> resourceHelper.gs(R.string.uel_treatment_removed)
            Action.TT_REMOVED.name                          -> resourceHelper.gs(R.string.uel_tt_removed)
            Action.NS_PAUSED.name                           -> resourceHelper.gs(R.string.uel_ns_paused)
            Action.NS_RESUME.name                           -> resourceHelper.gs(R.string.uel_ns_resume)
            Action.NS_QUEUE_CLEARED.name                    -> resourceHelper.gs(R.string.uel_ns_queue_cleared)
            Action.NS_SETTINGS_COPIED.name                  -> resourceHelper.gs(R.string.uel_ns_settings_copied)
            Action.ERROR_DIALOG_OK.name                     -> resourceHelper.gs(R.string.uel_error_dialog_ok)
            Action.ERROR_DIALOG_MUTE.name                   -> resourceHelper.gs(R.string.uel_error_dialog_mute)
            Action.ERROR_DIALOG_MUTE_5MIN.name              -> resourceHelper.gs(R.string.uel_error_dialog_mute_5min)
            Action.OBJECTIVE_STARTED.name                   -> resourceHelper.gs(R.string.uel_objective_started)
            Action.OBJECTIVE_UNSTARTED.name                 -> resourceHelper.gs(R.string.uel_objective_unstarted)
            Action.OBJECTIVES_SKIPPED.name                  -> resourceHelper.gs(R.string.uel_objectives_skipped)
            Action.STAT_RESET.name                          -> resourceHelper.gs(R.string.uel_stat_reset)
            Action.DELETE_LOGS.name                         -> resourceHelper.gs(R.string.uel_delete_logs)
            Action.DELETE_FUTURE_TREATMENTS.name            -> resourceHelper.gs(R.string.uel_delete_future_treatments)
            Action.EXPORT_SETTINGS.name                     -> resourceHelper.gs(R.string.uel_export_settings)
            Action.IMPORT_SETTINGS.name                     -> resourceHelper.gs(R.string.uel_import_settings)
            Action.RESET_DATABASES.name                     -> resourceHelper.gs(R.string.uel_reset_databases)
            Action.EXPORT_DATABASES.name                    -> resourceHelper.gs(R.string.uel_export_databases)
            Action.IMPORT_DATABASES.name                    -> resourceHelper.gs(R.string.uel_import_databases)
            Action.OTP_EXPORT.name                          -> resourceHelper.gs(R.string.uel_otp_export)
            Action.OTP_RESET.name                           -> resourceHelper.gs(R.string.uel_otp_reset)
            Action.SMS_BASAL.name                           -> resourceHelper.gs(R.string.uel_sms_basal)
            Action.SMS_BOLUS.name                           -> resourceHelper.gs(R.string.uel_sms_bolus)
            Action.SMS_CAL.name                             -> resourceHelper.gs(R.string.uel_sms_cal)
            Action.SMS_CARBS.name                           -> resourceHelper.gs(R.string.uel_sms_carbs)
            Action.SMS_EXTENDED_BOLUS.name                  -> resourceHelper.gs(R.string.uel_sms_extended_bolus)
            Action.SMS_LOOP_DISABLED.name                   -> resourceHelper.gs(R.string.uel_sms_loop_disabled)
            Action.SMS_LOOP_ENABLED.name                    -> resourceHelper.gs(R.string.uel_sms_loop_enabled)
            Action.SMS_LOOP_RESUME.name                     -> resourceHelper.gs(R.string.uel_sms_loop_resume)
            Action.SMS_LOOP_SUSPEND.name                    -> resourceHelper.gs(R.string.uel_sms_loop_suspend)
            Action.SMS_PROFILE.name                         -> resourceHelper.gs(R.string.uel_sms_profile)
            Action.SMS_PUMP_CONNECT.name                    -> resourceHelper.gs(R.string.uel_sms_pump_connect)
            Action.SMS_PUMP_DISCONNECT.name                 -> resourceHelper.gs(R.string.uel_sms_pump_disconnect)
            Action.SMS_SMS.name                             -> resourceHelper.gs(R.string.uel_sms_sms)
            Action.SMS_TT.name                              -> resourceHelper.gs(R.string.uel_sms_tt)
            Action.TT_DELETED_FROM_NS.name                  -> resourceHelper.gs(R.string.uel_tt_deleted_from_ns)
            Action.TT_FROM_NS.name                          -> resourceHelper.gs(R.string.uel_tt_from_ns)
            Action.TT_CANCELED_FROM_NS.name                 -> resourceHelper.gs(R.string.uel_tt_canceleted_from_ns)
            Action.CAREPORTAL_DELETED_FROM_NS.name          -> resourceHelper.gs(R.string.uel_careportal_deleted_from_ns)
            Action.CAREPORTAL_FROM_NS.name                  -> resourceHelper.gs(R.string.uel_careportal_from_ns)
            Action.EXPORT_CSV.name                          -> resourceHelper.gs(R.string.uel_export_csv)

            Units.Mg_Dl.name                                -> resourceHelper.gs(R.string.mgdl)
            Units.Mmol_L.name                               -> resourceHelper.gs(R.string.mmol)
            Units.U.name                                    -> resourceHelper.gs(R.string.insulin_unit_shortname)
            Units.U_H.name                                  -> resourceHelper.gs(R.string.profile_ins_units_per_hour)
            Units.G.name                                    -> resourceHelper.gs(R.string.shortgram)
            Units.M.name                                    -> resourceHelper.gs(R.string.shortminute)
            Units.H.name                                    -> resourceHelper.gs(R.string.shorthour)
            Units.Percent.name                              -> resourceHelper.gs(R.string.shortpercent)
            Units.None.name                                 -> ""

            else                                           -> resourceHelper.gs(R.string.unknown)
        }
}