package app.aaps.shared.impl.weardata

enum class JsonKeys(
    val key: String,
) {
    METADATA("metadata"),
    ENABLESECOND("enableSecond"),
    HIGHCOLOR("highColor"),
    MIDCOLOR("midColor"),
    LOWCOLOR("lowColor"),
    LOWBATCOLOR("lowBatColor"),
    CARBCOLOR("carbColor"),
    BASALBACKGROUNDCOLOR("basalBackgroundColor"),
    BASALCENTERCOLOR("basalCenterColor"),
    GRIDCOLOR("gridColor"),
    TEMPTARGETCOLOR("tempTargetColor"),
    TEMPTARGETLOOPCOLOR("tempTargetLoopColor"),
    TEMPTARGETPROFILECOLOR("tempTargetProfileColor"),
    RESERVOIRCOLOR("reservoirColor"),
    RESERVOIRWARNINGCOLOR("reservoirWarningColor"),
    RESERVOIRURGENTCOLOR("reservoirUrgentColor"),
    POINTSIZE("pointSize"),
    WIDTH("width"),
    HEIGHT("height"),
    TOPMARGIN("topmargin"),
    LEFTMARGIN("leftmargin"),
    ROTATION("rotation"),
    VISIBILITY("visibility"),
    TEXTSIZE("textsize"),
    TEXTVALUE("textvalue"),
    GRAVITY("gravity"),
    FONT("font"),
    FONTSTYLE("fontStyle"),
    FONTCOLOR("fontColor"),
    COLOR("color"),
    ALLCAPS("allCaps"),
    DAYNAMEFORMAT("dayNameFormat"),
    MONTHFORMAT("monthFormat"),
    BACKGROUND("background"), // Background image for textView
    LEFTOFFSET("leftOffset"),
    TOPOFFSET("topOffset"),
    ROTATIONOFFSET("rotationOffset"),
    DYNVALUE("dynValue"),
    DYNDATA("dynData"),
    VALUEKEY("valueKey"),
    MINDATA("minData"),
    MAXDATA("maxData"),
    MINVALUE("minValue"),
    MAXVALUE("maxValue"), //
    INVALIDVALUE("invalidValue"),
    IMAGE("image"),
    INVALIDIMAGE("invalidImage"),
    INVALIDCOLOR("invalidColor"),
    INVALIDFONTCOLOR("invalidFontColor"),
    INVALIDTEXTSIZE("invalidTextSize"),
    TWINVIEW("twinView"),
    TOPOFFSETTWINHIDDEN("topOffsetTwinHidden"),
    LEFTOFFSETTWINHIDDEN("leftOffsetTwinHidden"),
    DYNPREF("dynPref"),
    DYNPREFCOLOR("dynPrefColor"),
    PREFKEY("prefKey"),
    INVALIDTOPOFFSET("invalidTopOffset"),
    INVALIDLEFTOFFSET("invalidLeftOffset"),
    INVALIDROTATIONOFFSET("invalidRotationOffset"),
    INVALIDTEXTVALUE("invalidTextvalue"),
    DEFAULT("default"),
}
