package app.aaps.runners

import android.app.Application
import android.content.Context
import androidx.test.runner.AndroidJUnitRunner
import app.aaps.di.BaseTestApp

/**
 * Instrumentation runner that swaps in [app.aaps.di.BaseTestApp] instead of `MainApp`.
 *
 * Was `HiltTestRunner`, naming `app.aaps.di.HiltTestApplication_Application` - a class generated by the
 * Hilt processor from `@CustomTestApplication(BaseTestApp::class)`. There is no Hilt and no generated
 * application now, so it names the real class directly and a typo would fail to compile rather than at
 * runtime.
 */
class AapsTestRunner : AndroidJUnitRunner() {

    override fun newApplication(cl: ClassLoader?, name: String?, context: Context?): Application =
        super.newApplication(cl, BaseTestApp::class.java.name, context)
}
