package app.aaps.runners

import android.app.Application
import android.content.Context
import androidx.test.runner.AndroidJUnitRunner

/**
 * Instrumentation runner that swaps in the Hilt test application generated from the
 * `@CustomTestApplication(BaseTestApp::class)`-annotated `HiltTestApplication` interface (Hilt names
 * the generated class after the annotated element → `HiltTestApplication_Application`). Referenced by
 * name because the class is generated by the Hilt annotation processor.
 */
class HiltTestRunner : AndroidJUnitRunner() {

    override fun newApplication(cl: ClassLoader?, name: String?, context: Context?): Application =
        super.newApplication(cl, "app.aaps.di.HiltTestApplication_Application", context)
}
