package app.aaps.implementation.utils

import app.aaps.core.data.model.RM
import app.aaps.core.data.model.TE
import app.aaps.core.data.model.TT
import app.aaps.core.data.ue.Action
import app.aaps.core.data.ue.Sources
import app.aaps.core.data.ue.ValueWithUnit
import app.aaps.core.interfaces.InterfacesStrings
import app.aaps.core.interfaces.resources.TextResolver
import app.aaps.core.interfaces.utils.Translator
import app.aaps.core.ui.UiStrings
import dev.zacsweers.metro.AppScope
import dev.zacsweers.metro.ContributesBinding
import dev.zacsweers.metro.Inject
import dev.zacsweers.metro.SingleIn

// Metro builds this now; Dagger gets it through a @Provides delegate in `:app`. Scoped with Metro's
// @SingleIn, not javax @Singleton - the graph is generated in `:app`, which has no Dagger interop, so
// a javax scope there is ignored and every read would build a new one.
@ContributesBinding(AppScope::class)
@SingleIn(AppScope::class)
class TranslatorImpl @Inject internal constructor(
    private val rh: TextResolver
) : Translator {

    override fun translate(action: Action): String = when (action) {
        Action.BOLUS                           -> rh.gs(UiStrings.uel_bolus)
        Action.BOLUS_CALCULATOR_RESULT         -> rh.gs(UiStrings.uel_bolus_calculator)
        Action.BOLUS_CALCULATOR_RESULT_REMOVED -> rh.gs(UiStrings.uel_bolus_calculator)
        Action.SMB                             -> rh.gs(UiStrings.smb_shortname)
        Action.BOLUS_ADVISOR                   -> rh.gs(UiStrings.uel_bolus_advisor)
        Action.EXTENDED_BOLUS                  -> rh.gs(UiStrings.uel_extended_bolus)
        Action.SUPERBOLUS_TBR                  -> rh.gs(UiStrings.uel_superbolus_tbr)
        Action.CARBS                           -> rh.gs(UiStrings.uel_carbs)
        Action.EXTENDED_CARBS                  -> rh.gs(InterfacesStrings.uel_extended_carbs)
        Action.TEMP_BASAL                      -> rh.gs(UiStrings.uel_temp_basal)
        Action.TT                              -> rh.gs(UiStrings.uel_tt)
        Action.NEW_PROFILE                     -> rh.gs(UiStrings.uel_new_profile)
        Action.CLONE_PROFILE                   -> rh.gs(UiStrings.uel_clone_profile)
        Action.STORE_PROFILE                   -> rh.gs(UiStrings.uel_store_profile)
        Action.PROFILE_SWITCH                  -> rh.gs(UiStrings.uel_profile_switch)
        Action.PROFILE_SWITCH_CLONED           -> rh.gs(UiStrings.uel_profile_switch_cloned)
        Action.CLOSED_LOOP_MODE                -> rh.gs(UiStrings.uel_closed_loop_mode)
        Action.LGS_LOOP_MODE                   -> rh.gs(UiStrings.uel_lgs_loop_mode)
        Action.OPEN_LOOP_MODE                  -> rh.gs(UiStrings.uel_open_loop_mode)
        Action.LOOP_DISABLED                   -> rh.gs(UiStrings.uel_loop_disabled)
        Action.LOOP_RESUME                     -> rh.gs(UiStrings.uel_loop_resumed)
        Action.PUMP_RUNNING                    -> rh.gs(UiStrings.uel_pump_running)
        Action.RECONNECT                       -> rh.gs(UiStrings.uel_reconnect)
        Action.DISCONNECT                      -> rh.gs(UiStrings.uel_disconnect)
        Action.RESUME                          -> rh.gs(UiStrings.uel_resume)
        Action.SUSPEND                         -> rh.gs(UiStrings.uel_suspend)
        Action.HW_PUMP_ALLOWED                 -> rh.gs(UiStrings.uel_hw_pump_allowed)
        Action.CLEAR_PAIRING_KEYS              -> rh.gs(UiStrings.uel_clear_pairing_keys)
        Action.ACCEPTS_TEMP_BASAL              -> rh.gs(UiStrings.uel_accepts_temp_basal)
        Action.CANCEL_TEMP_BASAL               -> rh.gs(UiStrings.uel_cancel_temp_basal)
        Action.CANCEL_BOLUS                    -> rh.gs(UiStrings.uel_cancel_bolus)
        Action.CANCEL_EXTENDED_BOLUS           -> rh.gs(UiStrings.uel_cancel_extended_bolus)
        Action.CANCEL_TT                       -> rh.gs(UiStrings.uel_cancel_tt)
        Action.CAREPORTAL                      -> rh.gs(UiStrings.uel_careportal)
        Action.SENSOR_LOCATION                 -> rh.gs(UiStrings.uel_sensor_location)
        Action.SITE_CHANGE                     -> rh.gs(UiStrings.uel_site_change)
        Action.SITE_LOCATION                   -> rh.gs(UiStrings.uel_site_location)
        Action.RESERVOIR_CHANGE                -> rh.gs(UiStrings.uel_reservoir_change)
        Action.CALIBRATION                     -> rh.gs(UiStrings.uel_calibration)
        Action.PRIME_BOLUS                     -> rh.gs(UiStrings.uel_prime_bolus)
        Action.TREATMENT                       -> rh.gs(UiStrings.uel_treatment)
        Action.CAREPORTAL_NS_REFRESH           -> rh.gs(UiStrings.uel_careportal_ns_refresh)
        Action.PROFILE_SWITCH_NS_REFRESH       -> rh.gs(UiStrings.uel_profile_switch_ns_refresh)
        Action.TREATMENTS_NS_REFRESH           -> rh.gs(UiStrings.uel_treatments_ns_refresh)
        Action.TT_NS_REFRESH                   -> rh.gs(UiStrings.uel_tt_ns_refresh)
        Action.AUTOMATION_REMOVED              -> rh.gs(UiStrings.uel_automation_removed)
        Action.BG_REMOVED                      -> rh.gs(UiStrings.uel_bg_removed)
        Action.CALIBRATION_REMOVED             -> rh.gs(UiStrings.uel_calibration_removed)
        Action.CAREPORTAL_REMOVED              -> rh.gs(UiStrings.uel_careportal_removed)
        Action.BOLUS_REMOVED                   -> rh.gs(UiStrings.uel_bolus_removed)
        Action.CARBS_REMOVED                   -> rh.gs(UiStrings.uel_carbs_removed)
        Action.TEMP_BASAL_REMOVED              -> rh.gs(UiStrings.uel_temp_basal_removed)
        Action.EXTENDED_BOLUS_REMOVED          -> rh.gs(UiStrings.uel_extended_bolus_removed)
        Action.FOOD                            -> rh.gs(UiStrings.uel_food)
        Action.FOOD_REMOVED                    -> rh.gs(UiStrings.uel_food_removed)
        Action.PROFILE_REMOVED                 -> rh.gs(UiStrings.uel_profile_removed)
        Action.PROFILE_SWITCH_REMOVED          -> rh.gs(UiStrings.uel_profile_switch_removed)
        Action.RESTART_EVENTS_REMOVED          -> rh.gs(UiStrings.uel_restart_events_removed)
        Action.TREATMENT_REMOVED               -> rh.gs(UiStrings.uel_treatment_removed)
        Action.TT_REMOVED                      -> rh.gs(UiStrings.uel_tt_removed)
        Action.NS_PAUSED                       -> rh.gs(UiStrings.uel_ns_paused)
        Action.NS_RESUME                       -> rh.gs(UiStrings.uel_ns_resume)
        Action.NS_QUEUE_CLEARED                -> rh.gs(UiStrings.uel_ns_queue_cleared)
        Action.NS_SETTINGS_COPIED              -> rh.gs(UiStrings.uel_ns_settings_copied)
        Action.ERROR_DIALOG_OK                 -> rh.gs(UiStrings.uel_error_dialog_ok)
        Action.ERROR_DIALOG_MUTE               -> rh.gs(UiStrings.uel_error_dialog_mute)
        Action.ERROR_DIALOG_MUTE_5MIN          -> rh.gs(UiStrings.uel_error_dialog_mute_5min)
        Action.OBJECTIVE_STARTED               -> rh.gs(UiStrings.uel_objective_started)
        Action.OBJECTIVE_UNSTARTED             -> rh.gs(UiStrings.uel_objective_unstarted)
        Action.OBJECTIVES_SKIPPED              -> rh.gs(UiStrings.uel_objectives_skipped)
        Action.STAT_RESET                      -> rh.gs(UiStrings.uel_stat_reset)
        Action.DELETE_LOGS                     -> rh.gs(UiStrings.uel_delete_logs)
        Action.DELETE_FUTURE_TREATMENTS        -> rh.gs(UiStrings.uel_delete_future_treatments)
        Action.EXPORT_SETTINGS                 -> rh.gs(UiStrings.uel_export_settings)
        Action.IMPORT_SETTINGS                 -> rh.gs(UiStrings.uel_import_settings)
        Action.SELECT_DIRECTORY                -> rh.gs(UiStrings.uel_select_directory)
        Action.RESET_DATABASES                 -> rh.gs(UiStrings.uel_reset_databases)
        Action.RESET_APS_RESULTS               -> rh.gs(UiStrings.uel_reset_aps_results)
        Action.CLEANUP_DATABASES               -> rh.gs(UiStrings.uel_cleanup_databases)
        Action.EXPORT_DATABASES                -> rh.gs(UiStrings.uel_export_databases)
        Action.IMPORT_DATABASES                -> rh.gs(UiStrings.uel_import_databases)
        Action.OTP_EXPORT                      -> rh.gs(UiStrings.uel_otp_export)
        Action.OTP_RESET                       -> rh.gs(UiStrings.uel_otp_reset)
        Action.EXPORT_CSV                      -> rh.gs(UiStrings.uel_export_csv)
        Action.STOP_SMS                        -> rh.gs(UiStrings.uel_stop_sms)
        Action.START_AAPS                      -> rh.gs(UiStrings.uel_start_aaps)
        Action.EXIT_AAPS                       -> rh.gs(UiStrings.uel_exit_aaps)
        Action.PLUGIN_ENABLED                  -> rh.gs(UiStrings.uel_plugin_enabled)
        Action.PLUGIN_DISABLED                 -> rh.gs(UiStrings.uel_plugin_disabled)
        Action.LOOP_CHANGE                     -> rh.gs(UiStrings.uel_loop_change)
        Action.LOOP_REMOVED                    -> rh.gs(UiStrings.uel_loop_removed)
        Action.RUNNING_MODE                    -> rh.gs(UiStrings.uel_running_mode)
        Action.RUNNING_MODE_REMOVED            -> rh.gs(UiStrings.uel_running_mode_removed)
        Action.RUNNING_MODE_UPDATED            -> rh.gs(UiStrings.uel_running_mode_updarted)
        Action.NEW_INSULIN                     -> rh.gs(UiStrings.uel_new_insulin)
        Action.STORE_INSULIN                   -> rh.gs(UiStrings.uel_store_insulin)
        Action.INSULIN_REMOVED                 -> rh.gs(UiStrings.uel_insulin_removed)
        Action.CHANGE_PUMP_INSULIN             -> rh.gs(UiStrings.uel_change_pump_insulin)
        Action.CHANGE_INSULIN_CONCENTRATION    -> rh.gs(UiStrings.uel_change_insulin_concentration)
        Action.SCENE_ACTIVATED                 -> rh.gs(UiStrings.uel_scene_activated)
        Action.SCENE_DEACTIVATED               -> rh.gs(UiStrings.uel_scene_deactivated)
        Action.REMOTE_CONFIG_CHANGED           -> rh.gs(UiStrings.uel_remote_config_changed)
        Action.UNKNOWN                         -> rh.gs(UiStrings.unknown)
    }

    override fun translate(units: ValueWithUnit?): String = when (units) {
        is ValueWithUnit.Gram        -> rh.gs(UiStrings.shortgram)
        is ValueWithUnit.Hour        -> rh.gs(InterfacesStrings.shorthour)
        is ValueWithUnit.Insulin     -> rh.gs(UiStrings.insulin_unit_shortname)
        is ValueWithUnit.Mgdl        -> rh.gs(UiStrings.mgdl)
        is ValueWithUnit.Minute      -> rh.gs(InterfacesStrings.shortminute)
        is ValueWithUnit.Mmoll       -> rh.gs(UiStrings.mmol)
        is ValueWithUnit.Percent     -> rh.gs(UiStrings.shortpercent)
        is ValueWithUnit.UnitPerHour -> rh.gs(InterfacesStrings.profile_ins_units_per_hour)
        else                         -> ""
    }

    override fun translate(meterType: TE.MeterType?): String = when (meterType) {
        TE.MeterType.FINGER -> rh.gs(UiStrings.glucosetype_finger)
        TE.MeterType.SENSOR -> rh.gs(UiStrings.glucosetype_sensor)
        TE.MeterType.MANUAL -> rh.gs(UiStrings.manual)

        else                -> rh.gs(UiStrings.unknown)
    }

    override fun translate(type: TE.Type?): String = when (type) {
        TE.Type.FINGER_STICK_BG_VALUE   -> rh.gs(UiStrings.careportal_bgcheck)
        TE.Type.SNACK_BOLUS             -> rh.gs(UiStrings.careportal_snackbolus)
        TE.Type.MEAL_BOLUS              -> rh.gs(UiStrings.careportal_mealbolus)
        TE.Type.CORRECTION_BOLUS        -> rh.gs(UiStrings.careportal_correctionbolus)
        TE.Type.CARBS_CORRECTION        -> rh.gs(UiStrings.careportal_carbscorrection)
        TE.Type.BOLUS_WIZARD            -> rh.gs(UiStrings.boluswizard)
        TE.Type.COMBO_BOLUS             -> rh.gs(UiStrings.careportal_combobolus)
        TE.Type.ANNOUNCEMENT            -> rh.gs(UiStrings.careportal_announcement)
        TE.Type.SETTINGS_EXPORT         -> rh.gs(UiStrings.careportal_settings_export)
        TE.Type.NOTE                    -> rh.gs(UiStrings.careportal_note)
        TE.Type.QUESTION                -> rh.gs(UiStrings.careportal_question)
        TE.Type.EXERCISE                -> rh.gs(UiStrings.careportal_exercise)
        TE.Type.CANNULA_CHANGE          -> rh.gs(UiStrings.careportal_pump_site_change)
        TE.Type.PUMP_BATTERY_CHANGE     -> rh.gs(UiStrings.pump_battery_change)
        TE.Type.SENSOR_STARTED          -> rh.gs(UiStrings.careportal_cgmsensorstart)
        TE.Type.SENSOR_STOPPED          -> rh.gs(UiStrings.careportal_cgm_sensor_stop)
        TE.Type.SENSOR_CHANGE           -> rh.gs(UiStrings.cgm_sensor_insert)
        TE.Type.INSULIN_CHANGE          -> rh.gs(UiStrings.careportal_insulin_cartridge_change)
        TE.Type.DAD_ALERT               -> rh.gs(UiStrings.careportal_dad_alert)
        TE.Type.TEMPORARY_BASAL_START   -> rh.gs(UiStrings.careportal_tempbasalstart)
        TE.Type.TEMPORARY_BASAL_END     -> rh.gs(UiStrings.careportal_tempbasalend)
        TE.Type.PROFILE_SWITCH          -> rh.gs(UiStrings.careportal_profileswitch)
        TE.Type.TEMPORARY_TARGET        -> rh.gs(UiStrings.temporary_target)
        TE.Type.TEMPORARY_TARGET_CANCEL -> rh.gs(UiStrings.careportal_temporarytargetcancel)
        TE.Type.APS_OFFLINE             -> rh.gs(UiStrings.careportal_openapsoffline)
        TE.Type.NS_MBG                  -> rh.gs(UiStrings.careportal_mbg)
        TE.Type.FALLING_ASLEEP          -> rh.gs(UiStrings.careportal_falling_asleep)
        TE.Type.WAKING_UP               -> rh.gs(UiStrings.careportal_waking_up)
        TE.Type.SICKNESS                -> rh.gs(UiStrings.careportal_sickness)
        TE.Type.STRESS                  -> rh.gs(UiStrings.careportal_stress)
        TE.Type.PRE_PERIOD              -> rh.gs(UiStrings.careportal_pre_period)
        TE.Type.ALCOHOL                 -> rh.gs(UiStrings.careportal_alcohol)
        TE.Type.CORTISONE               -> rh.gs(UiStrings.careportal_cortisone)
        TE.Type.FEELING_LOW             -> rh.gs(UiStrings.careportal_feeling_low)
        TE.Type.FEELING_HIGH            -> rh.gs(UiStrings.careportal_feeling_high)
        TE.Type.NONE                    -> rh.gs(UiStrings.unknown)

        else                            -> rh.gs(UiStrings.unknown)
    }

    override fun translate(location: TE.Location?): String = when (location) {
        TE.Location.FRONT_RIGHT_UPPER_CHEST   -> rh.gs(UiStrings.location_front_right_upper_chest)
        TE.Location.FRONT_LEFT_UPPER_CHEST    -> rh.gs(UiStrings.location_front_left_upper_chest)
        TE.Location.SIDE_RIGHT_UPPER_ARM      -> rh.gs(UiStrings.location_side_right_upper_arm)
        TE.Location.SIDE_LEFT_UPPER_ARM       -> rh.gs(UiStrings.location_side_left_upper_arm)
        TE.Location.BACK_RIGHT_UPPER_ARM      -> rh.gs(UiStrings.location_back_right_upper_arm)
        TE.Location.BACK_LEFT_UPPER_ARM       -> rh.gs(UiStrings.location_back_left_upper_arm)
        TE.Location.SIDE_RIGHT_UPPER_ABDOMEN  -> rh.gs(UiStrings.location_side_right_upper_abdomen)
        TE.Location.SIDE_LEFT_UPPER_ABDOMEN   -> rh.gs(UiStrings.location_side_left_upper_abdomen)
        TE.Location.SIDE_RIGHT_LOWER_ABDOMEN  -> rh.gs(UiStrings.location_side_right_lower_abdomen)
        TE.Location.SIDE_LEFT_LOWER_ABDOMEN   -> rh.gs(UiStrings.location_side_left_lower_abdomen)
        TE.Location.FRONT_RIGHT_UPPER_ABDOMEN -> rh.gs(UiStrings.location_front_right_upper_abdomen)
        TE.Location.FRONT_LEFT_UPPER_ABDOMEN  -> rh.gs(UiStrings.location_front_left_upper_abdomen)
        TE.Location.FRONT_RIGHT_LOWER_ABDOMEN -> rh.gs(UiStrings.location_front_right_lower_abdomen)
        TE.Location.FRONT_LEFT_LOWER_ABDOMEN  -> rh.gs(UiStrings.location_front_left_lower_abdomen)
        TE.Location.BACK_RIGHT_BUTTOCK        -> rh.gs(UiStrings.location_back_right_buttock)
        TE.Location.BACK_LEFT_BUTTOCK         -> rh.gs(UiStrings.location_back_left_buttock)
        TE.Location.BACK_RIGHT_LOWER_BACK     -> rh.gs(UiStrings.location_back_right_lower_back)
        TE.Location.BACK_LEFT_LOWER_BACK      -> rh.gs(UiStrings.location_back_left_lower_back)
        TE.Location.FRONT_RIGHT_UPPER_THIGH   -> rh.gs(UiStrings.location_front_right_upper_thigh)
        TE.Location.FRONT_LEFT_UPPER_THIGH    -> rh.gs(UiStrings.location_front_left_upper_thigh)
        TE.Location.FRONT_RIGHT_LOWER_THIGH   -> rh.gs(UiStrings.location_front_right_lower_thigh)
        TE.Location.FRONT_LEFT_LOWER_THIGH    -> rh.gs(UiStrings.location_front_left_lower_thigh)
        TE.Location.SIDE_RIGHT_UPPER_THIGH    -> rh.gs(UiStrings.location_side_right_upper_thigh)
        TE.Location.SIDE_LEFT_UPPER_THIGH     -> rh.gs(UiStrings.location_side_left_upper_thigh)
        TE.Location.SIDE_RIGHT_LOWER_THIGH    -> rh.gs(UiStrings.location_side_right_lower_thigh)
        TE.Location.SIDE_LEFT_LOWER_THIGH     -> rh.gs(UiStrings.location_side_left_lower_thigh)
        TE.Location.NONE                      -> rh.gs(UiStrings.unknown)
        else                                  -> rh.gs(UiStrings.unknown)
    }

    override fun translate(arrow: TE.Arrow?): String = when (arrow) {
        TE.Arrow.UP         -> rh.gs(UiStrings.arrow_up)
        TE.Arrow.UP_RIGHT   -> rh.gs(UiStrings.arrow_up_right)
        TE.Arrow.RIGHT      -> rh.gs(UiStrings.arrow_right)
        TE.Arrow.DOWN_RIGHT -> rh.gs(UiStrings.arrow_down_right)
        TE.Arrow.DOWN       -> rh.gs(UiStrings.arrow_down)
        TE.Arrow.DOWN_LEFT  -> rh.gs(UiStrings.arrow_down_left)
        TE.Arrow.LEFT       -> rh.gs(UiStrings.arrow_left)
        TE.Arrow.UP_LEFT    -> rh.gs(UiStrings.arrow_up_left)
        TE.Arrow.CENTER     -> rh.gs(UiStrings.arrow_center)
        TE.Arrow.NONE       -> rh.gs(UiStrings.unknown)
        else                -> rh.gs(UiStrings.unknown)
    }

    override fun translate(reason: TT.Reason?): String = when (reason) {
        TT.Reason.CUSTOM       -> rh.gs(UiStrings.custom)
        TT.Reason.HYPOGLYCEMIA -> rh.gs(UiStrings.hypo)
        TT.Reason.EATING_SOON  -> rh.gs(UiStrings.eatingsoon)
        TT.Reason.ACTIVITY     -> rh.gs(UiStrings.activity)
        TT.Reason.AUTOMATION   -> rh.gs(UiStrings.automation)
        TT.Reason.WEAR         -> rh.gs(UiStrings.wear)

        else                   -> rh.gs(UiStrings.unknown)
    }

    override fun translate(mode: RM.Mode?): String = when (mode) {
        RM.Mode.DISABLED_LOOP     -> rh.gs(UiStrings.disabled_loop)
        RM.Mode.OPEN_LOOP         -> rh.gs(UiStrings.openloop)
        RM.Mode.CLOSED_LOOP       -> rh.gs(UiStrings.closedloop)
        RM.Mode.CLOSED_LOOP_LGS   -> rh.gs(UiStrings.lowglucosesuspend)
        RM.Mode.SUPER_BOLUS       -> rh.gs(UiStrings.superbolus)
        RM.Mode.DISCONNECTED_PUMP -> rh.gs(InterfacesStrings.pump_disconnected)
        RM.Mode.SUSPENDED_BY_PUMP -> rh.gs(UiStrings.pump_suspended)
        RM.Mode.SUSPENDED_BY_USER -> rh.gs(InterfacesStrings.loopsuspended)
        RM.Mode.SUSPENDED_BY_DST  -> rh.gs(UiStrings.loop_suspended_by_dst)
        RM.Mode.RESUME            -> rh.gs(UiStrings.resumeloop)
        null                      -> ""
    }

    override fun translate(source: Sources): String = when (source) {
        /*
        Sources.TreatmentDialog                    -> TODO()
        Sources.InsulinDialog                      -> TODO()
        Sources.CarbDialog                         -> TODO()
        Sources.WizardDialog                       -> TODO()
        Sources.QuickWizard                        -> TODO()
        Sources.ExtendedBolusDialog                -> TODO()
        Sources.TTDialog                           -> TODO()
        Sources.ProfileSwitchDialog                -> TODO()
        Sources.LoopDialog                         -> TODO()
        Sources.TempBasalDialog                    -> TODO()
        Sources.CalibrationDialog                  -> TODO()
        Sources.FillDialog                         -> TODO()

        Sources.BgCheck                            -> TODO()
        Sources.SensorInsert                       -> TODO()
        Sources.BatteryChange                      -> TODO()
        Sources.Note                               -> TODO()
        Sources.Exercise                           -> TODO()
        Sources.Question                           -> TODO()
        Sources.Announcement                       -> TODO()
        Sources.Actions                            -> TODO()
        Sources.BG                                 -> TODO()
        Sources.LocalProfile                       -> TODO()
        Sources.Maintenance                        -> TODO()
        Sources.NSProfile                          -> TODO()
        Sources.Objectives                         -> TODO()
        Sources.Treatments                         -> TODO()
        Sources.Food                               -> TODO()
        Sources.ConfigBuilder                      -> TODO()
        Sources.Overview                           -> TODO()
        Sources.Stats                              -> TODO()
        Sources.TreatmentDialog                    -> TODO()
        Sources.InsulinDialog                      -> TODO()
        Sources.CarbDialog                         -> TODO()
        Sources.WizardDialog                       -> TODO()
        Sources.QuickWizard                        -> TODO()
        Sources.ExtendedBolusDialog                -> TODO()
        Sources.TTDialog                           -> TODO()
        Sources.ProfileSwitchDialog                -> TODO()
        Sources.LoopDialog                         -> TODO()
        Sources.TempBasalDialog                    -> TODO()
        Sources.CalibrationDialog                  -> TODO()
        Sources.FillDialog                         -> TODO()
        Sources.BgCheck                            -> TODO()
        Sources.SensorInsert                       -> TODO()
        Sources.BatteryChange                      -> TODO()
        Sources.Note                               -> TODO()
        Sources.Exercise                           -> TODO()
        Sources.Question                           -> TODO()
        Sources.Announcement                       -> TODO()
        Sources.Actions                            -> TODO()
        Sources.BG                                 -> TODO()
        Sources.Dexcom                             -> TODO()
        Sources.Eversense                          -> TODO()
        Sources.Glimp                              -> TODO()
        Sources.MM640g                             -> TODO()
        Sources.NSClientSource                     -> TODO()
        Sources.PocTech                            -> TODO()
        Sources.Aidex                              -> TODO()
        Sources.Tomato                             -> TODO()
        Sources.Xdrip                              -> TODO()
        Sources.LocalProfile                       -> TODO()
        Sources.Maintenance                        -> TODO()
        Sources.NSProfile                          -> TODO()
        Sources.Objectives                         -> TODO()
        Sources.Dana                               -> TODO()
        Sources.DanaR                              -> TODO()
        Sources.DanaRC                             -> TODO()
        Sources.DanaRv2                            -> TODO()
        Sources.DanaRS                             -> TODO()
        Sources.DanaI                              -> TODO()
        Sources.DiaconnG8                          -> TODO()
        Sources.Insight                            -> TODO()
        Sources.Combo                              -> TODO()
        Sources.Medtronic                          -> TODO()
        Sources.Omnipod                            -> TODO()
        Sources.OmnipodEros                        -> TODO()
        Sources.OmnipodDash                        -> TODO()
        Sources.MDI                                -> TODO()
        Sources.VirtualPump                        -> TODO()
        Sources.Treatments                         -> TODO()
        Sources.Food                               -> TODO()
        Sources.ConfigBuilder                      -> TODO()
        Sources.Overview                           -> TODO()
        Sources.Stats                              -> TODO()
        Sources.Aaps                               -> TODO()
        */
        Sources.Automation     -> rh.gs(UiStrings.automation)
        Sources.SettingsExport -> rh.gs(UiStrings.settingsexport)
        Sources.Autotune       -> rh.gs(UiStrings.autotune)
        Sources.Loop           -> rh.gs(UiStrings.loop)
        Sources.NSClient       -> rh.gs(UiStrings.ns)
        Sources.Pump           -> rh.gs(UiStrings.pump)
        Sources.SMS            -> rh.gs(UiStrings.sms)
        Sources.Wear           -> rh.gs(UiStrings.wear)
        Sources.Unknown        -> rh.gs(UiStrings.unknown)

        else                   -> source.name
    }
}
