import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Writes the version a shell reports, from the same constant the Android app uses.
 *
 * ## Why this exists
 *
 * Android reads `BuildConfig.VERSION_NAME`, which AGP fills from `Versions.appVersion`. A plain JVM
 * or Kotlin/Native module has no `BuildConfig`, so the iOS and desktop shells each carried a
 * hardcoded placeholder - "0.0-ios" and "0.0-desktop" - and the About dialog showed it. A version
 * that is a placeholder is worse than none: a user reporting a problem quotes it, and it says
 * nothing about which build they are on.
 *
 * Generating it from `Versions.appVersion` means all three platforms report the same string, and a
 * release bump reaches them together.
 */
abstract class GenerateBuildInfoTask : DefaultTask() {

    /** The app version, normally `Versions.appVersion`. */
    @get:Input
    abstract val version: Property<String>

    /**
     * Which build this is - "Desktop" or "iOS".
     *
     * Shown as its own line in the About dialog, because the same version string now appears on
     * three platforms and the user needs to say which one they are running.
     */
    @get:Input
    abstract val platform: Property<String>

    /** Package for the generated object. Usually the shell's own config package. */
    @get:Input
    abstract val packageName: Property<String>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val dir = outputDir.get().asFile
        dir.deleteRecursively()
        val pkg = packageName.get()
        val file = File(dir, pkg.replace('.', '/') + "/GeneratedBuildInfo.kt")
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// Generated by GenerateBuildInfoTask from Versions.appVersion. Do not edit.
            |
            |package $pkg
            |
            |/**
            | * What this build calls itself.
            | *
            | * The same version string the Android app reports, so a bug report names one build whichever
            | * platform it came from.
            | */
            |object GeneratedBuildInfo {
            |
            |    const val VERSION: String = "${version.get()}"
            |
            |    /** "Desktop" or "iOS". Android does not set one, and shows no platform line. */
            |    const val PLATFORM: String = "${platform.get()}"
            |}
            |
            """.trimMargin()
        )
    }
}
