import org.gradle.api.DefaultTask
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction

/**
 * Writes the two version numbers Xcode needs, from the same constant every other platform reports.
 *
 * ## Why this is generated rather than typed into the project
 *
 * Both targets shipped with the Xcode template's placeholders - `MARKETING_VERSION = 1.0` and
 * `CURRENT_PROJECT_VERSION = 1`. Uploading twice with those is not merely untidy: App Store Connect
 * rejects a build whose `CFBundleVersion` is not **higher** than every build already uploaded for
 * that marketing version, so the second upload fails and the reason is easy to misread as a signing
 * problem.
 *
 * ## The two fields are not the same thing
 *
 * - [marketingVersion] is `CFBundleShortVersionString`, what a tester sees. It must be one to three
 *   plain integers, so `Versions.appVersion` cannot be used as it stands: `4.0.0-dev-b-kmp` is
 *   rejected. Only the numeric part goes here, and the full string stays in the About dialog where
 *   it is free to say which branch a build came from.
 * - [buildNumber] is `CFBundleVersion`, which only has to increase. Also at most three integers, so
 *   sticking the build number onto the end of the version - `4.0.0.<n>` - is not a valid value for
 *   either field.
 *
 * ## Why minutes since a fixed epoch
 *
 * It always increases, needs nothing stored between builds, and - unlike a commit count - still goes
 * up when the same commit is archived twice, which happens whenever an upload fails and is retried.
 *
 * Minutes **within the current month** would reset to nearly zero every 1st, making that day's build
 * lower than the previous month's and rejected. Any clock used here has to run from a fixed point,
 * never from a period boundary.
 */
abstract class GenerateVersionXcconfigTask : DefaultTask() {

    /** Normally `Versions.appVersion`; everything from the first `-` onward is dropped. */
    @get:Input
    abstract val version: Property<String>

    /** Minutes since the epoch below. Passed in so the task stays reproducible for a given minute. */
    @get:Input
    abstract val buildNumber: Property<Long>

    @get:OutputFile
    abstract val outputFile: RegularFileProperty

    @TaskAction
    fun generate() {
        val marketing = marketingVersionOf(version.get())
        outputFile.get().asFile.also { it.parentFile.mkdirs() }.writeText(
            """
            // Generated by :ios:shell:generateIosVersionXcconfig - do not edit, and do not commit.
            //
            // Deliberately not MARKETING_VERSION and CURRENT_PROJECT_VERSION directly: those are set
            // on the targets, and a target setting beats an xcconfig base configuration, so writing
            // them here would be read by nothing. The targets reference these two instead, each with
            // a default for a clone that has never generated this file.
            //
            // AAPS_MARKETING_VERSION is what a tester sees. AAPS_BUILD_NUMBER only has to increase,
            // and is minutes since $EPOCH_DESCRIPTION.
            AAPS_MARKETING_VERSION = $marketing
            AAPS_BUILD_NUMBER = ${buildNumber.get()}
            """.trimIndent() + "\n"
        )
    }

    companion object {

        const val EPOCH_DESCRIPTION = "2024-01-01"

        /** Milliseconds at [EPOCH_DESCRIPTION], UTC. Fixed forever: moving it would lower every build number. */
        const val EPOCH_MILLIS = 1_704_067_200_000L

        /**
         * The store-legal part of a version string.
         *
         * `4.0.0-dev-b-kmp` becomes `4.0.0`. A version with no numeric part at all falls back to
         * `0.0.1` rather than writing something Xcode would reject, because a build that fails at
         * upload time is worse than one that is honestly numbered zero.
         */
        fun marketingVersionOf(raw: String): String {
            val numeric = raw.substringBefore('-').trim()
            val parts = numeric.split('.').filter { it.isNotEmpty() && it.all(Char::isDigit) }
            return if (parts.isEmpty()) "0.0.1" else parts.take(3).joinToString(".")
        }

        /** Minutes from [EPOCH_MILLIS] to [now], never negative. */
        fun buildNumberFor(now: Long): Long = ((now - EPOCH_MILLIS).coerceAtLeast(0L)) / 60_000L
    }
}
