import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Writes the version a shell reports, from the same constant the Android app uses.
 *
 * ## Why this exists
 *
 * Android reads `BuildConfig.VERSION_NAME`, which AGP fills from `Versions.appVersion`. A plain JVM
 * or Kotlin/Native module has no `BuildConfig`, so the iOS and desktop shells each carried a
 * hardcoded placeholder - "0.0-ios" and "0.0-desktop" - and the About dialog showed it. A version
 * that is a placeholder is worse than none: a user reporting a problem quotes it, and it says
 * nothing about which build they are on.
 *
 * Generating it from `Versions.appVersion` means all three platforms report the same string, and a
 * release bump reaches them together.
 */
abstract class GenerateBuildInfoTask : DefaultTask() {

    /** The app version, normally `Versions.appVersion`. */
    @get:Input
    abstract val version: Property<String>

    /**
     * The build stamp: short commit and date, as `<hash>-<yyyy.MM.dd>`.
     *
     * The same shape `:app` puts in `BuildConfig.BUILDVERSION`, because the About dialog shows it as
     * "Build:" and the whole point of that line is to name the commit a user is running. Showing the
     * version there instead - which is already on the line above - would waste the line.
     */
    @get:Input
    abstract val buildStamp: Property<String>

    /**
     * Which build this is - "Desktop" or "iOS".
     *
     * Shown as its own line in the About dialog, because the same version string now appears on
     * three platforms and the user needs to say which one they are running.
     */
    @get:Input
    abstract val platform: Property<String>

    /** Package for the generated object. Usually the shell's own config package. */
    @get:Input
    abstract val packageName: Property<String>

    /**
     * Which client this build is: 1, 2 or 3.
     *
     * The desktop equivalent of Android's `aapsclient` flavours, and it decides more than a name.
     * Each client keeps its own database, preferences and keys, exactly as each Android client is a
     * separate app with its own private directory - so two of them can run against two Nightscout
     * sites at once. It is a build input rather than a command line flag because the packaged app
     * needs its own name and its own icon, and jpackage settles both when the installer is built.
     *
     * Defaults to 1, which is what iOS and an ordinary desktop build want.
     */
    @get:Input
    abstract val client: Property<Int>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    init {
        // So the iOS shell, and any build that does not care, needs to say nothing.
        client.convention(1)
    }

    @TaskAction
    fun generate() {
        val dir = outputDir.get().asFile
        dir.deleteRecursively()
        val pkg = packageName.get()
        val file = File(dir, pkg.replace('.', '/') + "/GeneratedBuildInfo.kt")
        file.parentFile.mkdirs()
        file.writeText(
            """
            |// Generated by GenerateBuildInfoTask from Versions.appVersion. Do not edit.
            |
            |package $pkg
            |
            |/**
            | * What this build calls itself.
            | *
            | * The same version string the Android app reports, so a bug report names one build whichever
            | * platform it came from.
            | */
            |object GeneratedBuildInfo {
            |
            |    const val VERSION: String = "${version.get()}"
            |
            |    /** Short commit and date, the same shape Android reports as "Build:". */
            |    const val BUILD: String = "${buildStamp.get()}"
            |
            |    /** "Desktop" or "iOS". Android does not set one, and shows no platform line. */
            |    const val PLATFORM: String = "${platform.get()}"
            |
            |    /**
            |     * Which client this build is: 1, 2 or 3.
            |     *
            |     * Decides the app name, the icon, and - the part that matters most - which data
            |     * directory it uses, so two clients never share one database.
            |     */
            |    const val CLIENT: Int = ${client.get()}
            |}
            |
            """.trimMargin()
        )
    }
}
