import org.gradle.api.DefaultTask
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.tasks.TaskAction
import java.io.File

/**
 * Writes the "which module owns which strings" registration, instead of each shell keeping a list.
 *
 * ## What it replaces
 *
 * A `TextRef.Named` carries an owner and a name, and the resolver needs to be told how to look a
 * name up for each owner. That registration was hand written four times - twice on Android, once for
 * iOS, once for desktop - and nothing compared the four with each other or with the build. The
 * desktop copy had five of sixteen modules, which showed up as a plugin list full of string names.
 *
 * Now every shell generates it from [StringOwnerModules], so adding a module means one line there.
 *
 * ## Two shapes, one list
 *
 * Android resolves through AAPT and wants the `R.string` id maps, which only exist in androidMain.
 * The other platforms have no resource table and want the generated English text maps, which are in
 * commonMain. Same list, two lookups, chosen with [useResourceIds].
 */
abstract class GenerateStringOwnerRegistryTask : DefaultTask() {

    /** The modules to register. Normally [StringOwnerModules.ALL]. */
    @get:Input
    abstract val owners: ListProperty<StringOwnerModule>

    /** Package for the generated object. Usually the shell's own package. */
    @get:Input
    abstract val packageName: Property<String>

    /** Name of the generated object, for example `GeneratedStringOwners`. */
    @get:Input
    abstract val objectName: Property<String>

    /**
     * True to register `R.string` id maps for Android, false to register the English text maps.
     *
     * Not a guess the task can make: both objects are generated for every module, and which one a
     * platform can actually use is what differs.
     */
    @get:Input
    abstract val useResourceIds: Property<Boolean>

    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @TaskAction
    fun generate() {
        val dir = outputDir.get().asFile
        dir.deleteRecursively()
        val pkg = packageName.get()
        val obj = objectName.get()
        val ids = useResourceIds.get()
        val modules = owners.get().sortedBy { it.owner }

        val registry = if (ids) "TextRefIdRegistry" else "TextRefValueRegistry"
        val lookup = if (ids) "idOf" else "textOf"

        val file = File(dir, pkg.replace('.', '/') + "/$obj.kt")
        file.parentFile.mkdirs()
        file.writeText(
            buildString {
                append("// Generated by GenerateStringOwnerRegistryTask from StringOwnerModules. Do not edit.\n\n")
                append("package $pkg\n\n")
                append("import app.aaps.core.interfaces.resources.$registry\n")
                modules.forEach {
                    val target = if (ids) it.idsObjectName else it.valuesObjectName
                    append("import ${it.packageName}.$target\n")
                }
                append("\n")
                append("/**\n")
                append(" * Tells the resolver which module owns which string names.\n")
                append(" *\n")
                if (ids) {
                    append(" * Android resolves a name to an `R.string` id and reads the text through `Resources`, so\n")
                    append(" * locale matching and every translation keep working exactly as before.\n")
                } else {
                    append(" * Registers the generated English text, for the platforms that have no resource table.\n")
                    append(" * Only the base locale exists in these maps; translating them is a separate job.\n")
                }
                append(" *\n")
                append(" * Generated from `StringOwnerModules.ALL`, so a module cannot be forgotten here - which is\n")
                append(" * what happened when each platform kept its own list.\n")
                append(" */\n")
                append("object $obj {\n\n")
                append("    /** Call once, before anything asks for text. */\n")
                append("    fun registerAll() {\n")
                modules.forEach {
                    val target = if (ids) it.idsObjectName else it.valuesObjectName
                    // The text lookup takes the locale the registry is currently set to; the Android
                    // id lookup does not, because AAPT does the locale matching there.
                    val args = if (ids) "name -> $target.$lookup(name)" else "name, locale -> $target.$lookup(name, locale)"
                    append("        $registry.register(\"${it.owner}\") { $args }\n")
                }
                append("    }\n")
                append("}\n")
            }
        )
    }
}
