package app.aaps.plugins.constraints.objectives.objectives

import app.aaps.core.ui.CoreUiStrings
import app.aaps.plugins.constraints.ConstraintsStrings
import app.aaps.core.interfaces.resources.ResourceHelper
import app.aaps.core.interfaces.utils.DateUtil
import app.aaps.core.keys.interfaces.Preferences
import dev.zacsweers.metro.AppScope
import dev.zacsweers.metro.ContributesIntoMap
import dev.zacsweers.metro.Inject
import dev.zacsweers.metro.IntKey
import dev.zacsweers.metro.SingleIn
import dev.zacsweers.metro.binding

@Suppress("SpellCheckingInspection")
// Contributed rather than listed in a graph. ObjectivesPlugin takes List<Objective> and is itself
// contributed to AppScope, so the objectives have to be reachable from the same graph.
@ContributesIntoMap(AppScope::class, binding = binding<Objective>())
@IntKey(2)
@SingleIn(AppScope::class)
class Objective2 @Inject constructor(
    preferences: Preferences,
    rh: ResourceHelper,
    dateUtil: DateUtil,
) : Objective(preferences, rh, dateUtil, "exam", ConstraintsStrings.objectives_exam_objective, ConstraintsStrings.objectives_exam_gate) {

    init {
        tasks.add(
            ExamTask(this, ConstraintsStrings.prerequisites_label, ConstraintsStrings.prerequisites_what, "prerequisites")
                .option(Option(ConstraintsStrings.prerequisites_nightscout, true))
                .option(Option(ConstraintsStrings.prerequisites_build, true))
                .option(Option(ConstraintsStrings.prerequisites_pump, true))
                .option(Option(ConstraintsStrings.prerequisites_beanandroiddeveloper, false))
                .hint(Hint(ConstraintsStrings.prerequisites_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_prerequisites))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.prerequisites2_label, ConstraintsStrings.prerequisites2_what, "prerequisites2")
                .option(Option(ConstraintsStrings.prerequisites2_profile, true))
                .option(Option(ConstraintsStrings.prerequisites2_device, true))
                .option(Option(ConstraintsStrings.prerequisites2_internet, false))
                .option(Option(ConstraintsStrings.prerequisites2_supportedcgm, true))
                .hint(Hint(ConstraintsStrings.prerequisites2_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_prerequisites2))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.basaltest_label, ConstraintsStrings.basaltest_when, "basaltest")
                .option(Option(ConstraintsStrings.basaltest_fixed, false))
                .option(Option(ConstraintsStrings.basaltest_havingregularhighlow, true))
                .option(Option(ConstraintsStrings.basaltest_weekly, false))
                .option(Option(ConstraintsStrings.basaltest_beforeloop, true))
                .hint(Hint(ConstraintsStrings.basaltest_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_basaltest))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.dia_label_exam, ConstraintsStrings.dia_whatmeansdia, "dia")
                .option(Option(ConstraintsStrings.dia_profile, true))
                .option(Option(ConstraintsStrings.dia_minimumis5h, true))
                .option(Option(ConstraintsStrings.dia_meaningisequaltodiapump, false))
                .option(Option(ConstraintsStrings.dia_valuemustbedetermined, true))
                .hint(Hint(ConstraintsStrings.dia_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_dia))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.isf_label_exam, ConstraintsStrings.blank, "isf")
                .option(Option(ConstraintsStrings.isf_decreasingvalue, true))
                .option(Option(ConstraintsStrings.isf_preferences, false))
                .option(Option(ConstraintsStrings.isf_increasingvalue, false))
                .option(Option(ConstraintsStrings.isf_noeffect, false))
                .hint(Hint(ConstraintsStrings.isf_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_isf))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.ic_label_exam, ConstraintsStrings.blank, "ic")
                .option(Option(ConstraintsStrings.ic_increasingvalue, true))
                .option(Option(ConstraintsStrings.ic_decreasingvalue, false))
                .option(Option(ConstraintsStrings.ic_multiple, true))
                .option(Option(ConstraintsStrings.ic_isf, false))
                .hint(Hint(ConstraintsStrings.ic_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_ic))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.hypott_label, ConstraintsStrings.hypott_whenhypott, "hypott")
                .option(Option(ConstraintsStrings.hypott_preventoversmb, true))
                .option(Option(ConstraintsStrings.hypott_exercise, false))
                .option(Option(ConstraintsStrings.hypott_wrongbasal, false))
                .option(Option(ConstraintsStrings.hypott_0basal, false))
                .hint(Hint(ConstraintsStrings.hypott_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_hypott))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.profileswitch_label, ConstraintsStrings.profileswitch_pctwillchange, "profileswitch")
                .option(Option(ConstraintsStrings.profileswitch_basallower, true))
                .option(Option(ConstraintsStrings.profileswitch_isfhigher, true))
                .option(Option(ConstraintsStrings.profileswitch_iclower, false))
                .option(Option(ConstraintsStrings.profileswitch_unchanged, false))
                .hint(Hint(ConstraintsStrings.profileswitch_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_profileswitch))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.profileswitch2_label, ConstraintsStrings.profileswitch2_pctwillchange, "profileswitch2")
                .option(Option(ConstraintsStrings.profileswitch2_bghigher, false))
                .option(Option(ConstraintsStrings.profileswitch2_basalhigher, true))
                .option(Option(ConstraintsStrings.profileswitch2_bgunchanged, true))
                .option(Option(ConstraintsStrings.profileswitch2_isfhigher, false))
                .hint(Hint(ConstraintsStrings.profileswitch_hint1))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.profileswitchtime_label, ConstraintsStrings.profileswitchtime_iwant, "profileswitchtime")
                .option(Option(ConstraintsStrings.profileswitchtime_2, false))
                .option(Option(ConstraintsStrings.profileswitchtime__2, true))
                .option(Option(ConstraintsStrings.profileswitchtime_tt, false))
                .option(Option(ConstraintsStrings.profileswitchtime_100, false))
                .hint(Hint(ConstraintsStrings.profileswitchtime_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_profileswitchtime))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.profileswitch4_label, ConstraintsStrings.blank, "profileswitch4")
                .option(Option(ConstraintsStrings.profileswitch4_rates, true))
                .option(Option(ConstraintsStrings.profileswitch4_internet, true))
                .option(Option(ConstraintsStrings.profileswitch4_sufficient, false))
                .option(Option(ConstraintsStrings.profileswitch4_multi, true))
                .hint(Hint(ConstraintsStrings.profileswitch_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_profileswitch4))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.exerciseprofile_label, ConstraintsStrings.exerciseprofile_whattodo, "exercise")
                .option(Option(ConstraintsStrings.exerciseprofile_switchprofileabove100, false))
                .option(Option(ConstraintsStrings.exerciseprofile_switchprofilebelow100, true))
                .option(Option(ConstraintsStrings.exerciseprofile_suspendloop, false))
                .option(Option(ConstraintsStrings.exerciseprofile_leaveat100, false))
                .hint(Hint(ConstraintsStrings.exerciseprofile_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_exercise))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.exercise_label, ConstraintsStrings.exercise_whattodo, "exercise2")
                .option(Option(ConstraintsStrings.exercise_settt, true))
                .option(Option(ConstraintsStrings.exercise_setfinished, false))
                .option(Option(ConstraintsStrings.exercise_setunchanged, false))
                .option(Option(ConstraintsStrings.exercise_15g, false))
                .hint(Hint(ConstraintsStrings.exercise_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_exercise2))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.noisycgm_label, ConstraintsStrings.noisycgm_whattodo, "noisycgm")
                .option(Option(ConstraintsStrings.noisycgm_nothing, false))
                .option(Option(ConstraintsStrings.noisycgm_pause, true))
                .option(Option(ConstraintsStrings.noisycgm_replacesensor, true))
                .option(Option(ConstraintsStrings.noisycgm_checksmoothing, true))
                .hint(Hint(ConstraintsStrings.noisycgm_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_noisycgm))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.pumpdisconnect_label, ConstraintsStrings.blank, "pumpdisconnect")
                .option(Option(ConstraintsStrings.pumpdisconnect_unnecessary, false))
                .option(Option(ConstraintsStrings.pumpdisconnect_missinginsulin, true))
                .option(Option(ConstraintsStrings.pumpdisconnect_notstop, false))
                .option(Option(ConstraintsStrings.pumpdisconnect_openloop, false))
                .hint(Hint(ConstraintsStrings.pumpdisconnect_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_pumpdisconnect))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.insulin_plugins, ConstraintsStrings.insulin_ultrarapid, "insulin")
                .option(Option(ConstraintsStrings.insulin_novorapid, false))
                .option(Option(ConstraintsStrings.insulin_humalog, false))
                .option(Option(ConstraintsStrings.insulin_actrapid, false))
                .option(Option(ConstraintsStrings.insulin_fiasp, true))
                .hint(Hint(ConstraintsStrings.insulin_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_insulin))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.sensitivity_label, ConstraintsStrings.blank, "sensitivity")
                .option(Option(ConstraintsStrings.sensitivity_adjust, true))
                .option(Option(ConstraintsStrings.sensitivity_edit, false))
                .option(Option(ConstraintsStrings.sensitivity_cannula, true))
                .option(Option(ConstraintsStrings.sensitivity_time, true))
                .hint(Hint(ConstraintsStrings.sensitivity_hint1))
                .hint(Hint(ConstraintsStrings.sensitivity_hint2))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_sensitivity))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.objectives_label, ConstraintsStrings.objectives_howtosave, "objectives")
                .option(Option(ConstraintsStrings.objectives_notesettings, false))
                .option(Option(ConstraintsStrings.objectives_afterobjective, true))
                .option(Option(ConstraintsStrings.objectives_afterchange, true))
                .option(Option(ConstraintsStrings.objectives_afterinitialsetup, true))
                .hint(Hint(ConstraintsStrings.objectives_hint1))
                .hint(Hint(ConstraintsStrings.objectives_hint2))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_objectives))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.objectives2_label, ConstraintsStrings.objectives_howtosave, "objectives2")
                .option(Option(ConstraintsStrings.objectives2_maintenance, true))
                .option(Option(ConstraintsStrings.objectives2_internalstorage, true))
                .option(Option(ConstraintsStrings.objectives2_cloud, true))
                .option(Option(ConstraintsStrings.objectives2_easyrestore, false))
                .hint(Hint(ConstraintsStrings.objectives_hint1))
                .hint(Hint(ConstraintsStrings.objectives_hint2))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_objectives2))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.update_label, ConstraintsStrings.blank, "update")
                .option(Option(ConstraintsStrings.update_git, true))
                .option(Option(ConstraintsStrings.update_askfriend, false))
                .option(Option(ConstraintsStrings.update_keys, true))
                .option(Option(ConstraintsStrings.update_asap, true))
                .hint(Hint(ConstraintsStrings.update_hint1))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.troubleshooting_label, ConstraintsStrings.troubleshooting_wheretoask, "troubleshooting")
                .option(Option(ConstraintsStrings.troubleshooting_fb, true))
                .option(Option(ConstraintsStrings.troubleshooting_wiki, true))
                .option(Option(ConstraintsStrings.troubleshooting_discord, true))
                .option(Option(ConstraintsStrings.troubleshooting_github, true))
                .option(Option(ConstraintsStrings.troubleshooting_yourendo, false))
                .hint(Hint(ConstraintsStrings.troubleshooting_hint1))
                .hint(Hint(ConstraintsStrings.troubleshooting_hint2))
                .hint(Hint(ConstraintsStrings.troubleshooting_hint3))
                .hint(Hint(ConstraintsStrings.troubleshooting_hint4))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.wrongcarbs_label, ConstraintsStrings.wrongcarbs_whattodo, "wrongcarbs")
                .option(Option(ConstraintsStrings.wrongcarbs_addinsulin, false))
                .option(Option(ConstraintsStrings.wrongcarbs_treatmentstab, true))
                .option(Option(ConstraintsStrings.wrongcarbs_donothing, false))
                .option(Option(ConstraintsStrings.wrongcarbs_bolus, false))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_wrongcarbs))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.wronginsulin_label, ConstraintsStrings.wronginsulin_whattodo, "wronginsulin")
                .option(Option(ConstraintsStrings.wronginsulin_careportal, false))
                .option(Option(ConstraintsStrings.wronginsulin_compare, true))
                .option(Option(ConstraintsStrings.wronginsulin_prime, true))
                .option(Option(ConstraintsStrings.wrongcarbs_donothing, false))
        )
        tasks.add(
            ExamTask(this, CoreUiStrings.iob_label, ConstraintsStrings.blank, "iob")
                .option(Option(ConstraintsStrings.iob_value, true))
                .option(Option(ConstraintsStrings.iob_hightemp, false))
                .option(Option(ConstraintsStrings.iob_negiob, true))
                .option(Option(ConstraintsStrings.iob_posiob, true))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_iob))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.cob_label, ConstraintsStrings.cob_question, "cob1")
                .option(Option(ConstraintsStrings.cob_longer, true))
                .option(Option(ConstraintsStrings.cob_shorter, false))
                .option(Option(ConstraintsStrings.cob_no_effect, false))
                .hint(Hint(ConstraintsStrings.cob_hint1))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.cob_label, ConstraintsStrings.cob2_question, "cob2")
                .option(Option(ConstraintsStrings.cob2_longer, false))
                .option(Option(ConstraintsStrings.cob2_shorter, true))
                .option(Option(ConstraintsStrings.cob2_no_effect, false))
                .hint(Hint(ConstraintsStrings.cob_hint1))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.cob_label, ConstraintsStrings.cob3_question, "cob3")
                .option(Option(ConstraintsStrings.cob3_longer, false))
                .option(Option(ConstraintsStrings.cob3_shorter, false))
                .option(Option(ConstraintsStrings.cob3_no_effect, true))
                .hint(Hint(ConstraintsStrings.cob_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_cob))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.breadgrams_label, ConstraintsStrings.blank, "breadgrams")
                .option(Option(ConstraintsStrings.breadgrams_grams, true))
                .option(Option(ConstraintsStrings.breadgrams_exchange, false))
                .option(Option(ConstraintsStrings.breadgrams_decay, true))
                .option(Option(ConstraintsStrings.breadgrams_calc, true))
                .hint(Hint(ConstraintsStrings.breadgrams_hint1))
                .hint(Hint(ConstraintsStrings.breadgrams_hint2))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_breadgrams))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.extendedcarbs_label, ConstraintsStrings.extendedcarbs_handling, "extendedcarbs")
                .option(Option(ConstraintsStrings.extendedcarbs_future, true))
                .option(Option(ConstraintsStrings.extendedcarbs_free, false))
                .option(Option(ConstraintsStrings.extendedcarbs_fat, true))
                .option(Option(ConstraintsStrings.extendedcarbs_rescue, false))
                .hint(Hint(ConstraintsStrings.extendedcarbs_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_ecarbs))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.nsclient_label, ConstraintsStrings.nsclient_howcanyou, "nsclient")
                .option(Option(ConstraintsStrings.nsclient_nightscout, true))
                .option(Option(ConstraintsStrings.nsclient_dexcomfollow, true))
                .option(Option(ConstraintsStrings.nsclient_data, true))
                .option(Option(ConstraintsStrings.nsclient_fullcontrol, false))
                .hint(Hint(ConstraintsStrings.nsclient_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_nsclient))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.other_medication_label, ConstraintsStrings.other_medication_text, "otherMedicationWarning")
                .option(Option(CoreUiStrings.yes, true))
                .option(Option(CoreUiStrings.no, false))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.concentration_feature_label, ConstraintsStrings.u200_with_profile, "concentration1")
                .option(Option(ConstraintsStrings.u200_with_profile_reports, true))
                .option(Option(ConstraintsStrings.u200_with_profile_pens, false))
                .option(Option(ConstraintsStrings.u200_with_profile_pens2, true))
                .hint(Hint(ConstraintsStrings.concentration_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_concentration1))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.concentration_feature_label, ConstraintsStrings.switch_u200_profile, "concentration2")
                .option(Option(ConstraintsStrings.switch_u200_profile_any_time, false))
                .option(Option(ConstraintsStrings.switch_u200_profile_ps, true))
                .option(Option(ConstraintsStrings.switch_u200_profile_dynisf, true))
                .option(Option(ConstraintsStrings.switch_u200_profile_mental, true))
                .hint(Hint(ConstraintsStrings.concentration_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_concentration2))
        )
        tasks.add(
            ExamTask(this, ConstraintsStrings.concentration_feature_label, ConstraintsStrings.switch_u100_u200, "concentration3")
                .option(Option(ConstraintsStrings.switch_u100_u200_profile, false))
                .option(Option(ConstraintsStrings.switch_u100_u200_tube, true))
                .option(Option(ConstraintsStrings.switch_u100_u200_pen, false))
                .option(Option(ConstraintsStrings.switch_u100_u200_change, true))
                .hint(Hint(ConstraintsStrings.concentration_hint1))
                .learned(Learned(ConstraintsStrings.objectives_exam_learned_concentration3))
        )
        for (task in tasks) (task as ExamTask).options.shuffle()

        // Tasks here are all ExamTasks whose isCompleted() simply returns `answered`.
        // Read the field directly to avoid suspending in init.
        for (task in tasks) {
            if (!(task as ExamTask).answered) accomplishedOn = 0
        }
    }
}