package app.aaps.pump.eopatch.core.code

enum class PatchBleResultCode {
    SUCCESS,
    BASAL_SCHEDULE_SET_NOT_SORTED,
    BASAL_SCHEDULE_SET_TIMEOUT,
    BASAL_SCHEDULE_FINISH_BUT_NOT_COMPLETED,
    BASAL_SCHEDULE_OVER_DOSE,
    BASAL_NOT_REGISTERED,
    BASAL_INSULIN_AMOUNT_LIMIT,
    BASAL_PERCENT_RANGE_INVALID,
    BOLUS_OTHER_RUNNING,
    BOLUS_OVERRUN,
    BOLUS_INVALID_RANGE,
    BOLUS_UNKNOWN_ID,
    BOLUS_NO_SUCH_ITEM,
    TEMP_BASAL_NOT_EXIST,
    TEMP_BASAL_NOT_FINISH,
    UNKNOWN_ERROR;

    val isSuccess: Boolean get() = this == SUCCESS
}
