package info.nightscout.androidaps.plugins.pump.eopatch.code

enum class EventType {
    ACTIVATION_CLICKED,
    DEACTIVATION_CLICKED,
    SUSPEND_CLICKED,
    RESUME_CLICKED,
    INVALID_BASAL_RATE,
    PROFILE_NOT_SET,
    SHOW_PATCH_COMM_DIALOG,
    DISMISS_PATCH_COMM_DIALOG,
    SHOW_PATCH_COMM_ERROR_DIALOG,
    SHOW_BONDED_DIALOG,
    SHOW_CHANGE_PATCH_DIALOG,
    FINISH_ACTIVITY,
    SHOW_DISCARD_DIALOG,
    PAUSE_BASAL_SUCCESS,
    PAUSE_BASAL_FAILED,
    RESUME_BASAL_SUCCESS,
    RESUME_BASAL_FAILED
    ;
}
