package app.aaps.core.interfaces.aps

import kotlinx.serialization.Serializable

@Serializable
data class OapsProfile(
    var dia: Double, // AMA only
    var min_5m_carbimpact: Double, // AMA only
    var max_iob: Double,
    var max_daily_basal: Double,
    var max_basal: Double,
    var min_bg: Double,
    var max_bg: Double,
    var target_bg: Double,
    var carb_ratio: Double,
    var sens: Double,
    var autosens_adjust_targets: Boolean, // AMA only
    var max_daily_safety_multiplier: Double,
    var current_basal_safety_multiplier: Double,
    var high_temptarget_raises_sensitivity: Boolean,
    var low_temptarget_lowers_sensitivity: Boolean,
    var sensitivity_raises_target: Boolean,
    var resistance_lowers_target: Boolean,
    var adv_target_adjustments: Boolean,
    var exercise_mode: Boolean,
    var half_basal_exercise_target: Int,
    var maxCOB: Int,
    var skip_neutral_temps: Boolean,
    var remainingCarbsCap: Int,
    var enableUAM: Boolean,
    var A52_risk_enable: Boolean,
    var SMBInterval: Int,
    var enableSMB_with_COB: Boolean,
    var enableSMB_with_temptarget: Boolean,
    var allowSMB_with_high_temptarget: Boolean,
    var enableSMB_always: Boolean,
    var enableSMB_after_carbs: Boolean,
    var maxSMBBasalMinutes: Int,
    var maxUAMSMBBasalMinutes: Int,
    var bolus_increment: Double,
    var carbsReqThreshold: Int,
    var current_basal: Double,
    var temptargetSet: Boolean,
    var autosens_max: Double,
    var out_units: String,
    var lgsThreshold: Int?,
    //DynISF only
    var variable_sens: Double,
    var insulinDivisor: Int,
    var TDD: Double,
    //AutoISF only
    var autoISF_version: String = "",
    var enable_autoISF: Boolean = true,
    var autoISF_max: Double = 1.0,
    var autoISF_min: Double = 1.0,
    var bgAccel_ISF_weight: Double = 0.0,
    var bgBrake_ISF_weight: Double = 0.0,
    var enable_pp_ISF_always: Boolean = false,
    var pp_ISF_hours:  Int = 3,
    var pp_ISF_weight: Double = 0.0,
    var delta_ISFrange_weight: Double = 0.0,
    var enable_dura_ISF_with_COB: Boolean = false,
    var dura_ISF_weight: Double = 0.0,
    var smb_delivery_ratio: Double = 0.5,
    var smb_delivery_ratio_min: Double = 0.5,
    var smb_delivery_ratio_max: Double = 0.5,
    var smb_delivery_ratio_bg_range: Double = 0.0,
    var smb_max_range_extension: Double = 1.0,
    var enableSMB_EvenOn_OddOff: Boolean = false,
    var enableSMB_EvenOn_OddOff_always: Boolean = false,
    var iob_threshold_percent: Int = 100,
    var profile_percentage: Int = 100
)