package app.aaps.plugins.aps.openAPS

data class Profile(
    var dia: Int, // AMA only
    var min_5m_carbimpact: Double, // AMA only
    var max_iob: Double,
    var type: String,
    var max_daily_basal: Double,
    var max_basal: Double,
    var min_bg: Double,
    var max_bg: Double,
    var target_bg: Double,
    var carb_ratio: Double,
    var sens: Double,
    var autosens_adjust_targets: Boolean, // AMA only
    var max_daily_safety_multiplier: Double,
    var current_basal_safety_multiplier: Double,
    var lgsThreshold: Int?,
    var high_temptarget_raises_sensitivity: Boolean,
    var low_temptarget_lowers_sensitivity: Boolean,
    var sensitivity_raises_target: Boolean,
    var resistance_lowers_target: Boolean,
    var adv_target_adjustments: Boolean,
    var exercise_mode: Boolean,
    var half_basal_exercise_target: Int,
    var maxCOB: Int,
    var skip_neutral_temps: Boolean,
    var remainingCarbsCap: Int,
    var enableUAM: Boolean,
    var A52_risk_enable: Boolean,
    var SMBInterval: Int,
    var enableSMB_with_COB: Boolean,
    var enableSMB_with_temptarget: Boolean,
    var allowSMB_with_high_temptarget: Boolean,
    var enableSMB_always: Boolean,
    var enableSMB_after_carbs: Boolean,
    var maxSMBBasalMinutes: Int,
    var maxUAMSMBBasalMinutes: Int,
    var bolus_increment: Double,
    var carbsReqThreshold: Int,
    var current_basal: Double,
    var temptargetSet: Boolean,
    var autosens_max: Double,
    var autosens_min: Double?,
    var out_units: String,
    var variable_sens: Double?, //DynISF + AutoISF only
    var insulinDivisor: Int?, //DynISF only
    var TDD: Double?, //DynISF only
    var autoISF_version: String? = null, // AutoISF only ... from here and downwards
    var enable_autoISF: Boolean? = null,
    var autoISF_max: Double? = null,
    var autoISF_min: Double? = null,
    var bgAccel_ISF_weight: Double? = null,
    var bgBrake_ISF_weight: Double? = null,
    var enable_pp_ISF_always: Boolean? = null,
    var pp_ISF_hours: Int? = null,
    var pp_ISF_weight: Double? = null,
    var delta_ISFrange_weight: Double? = null,
    var lower_ISFrange_weight: Double? = null,
    var higher_ISFrange_weight: Double? = null,
    var enable_dura_ISF_with_COB: Boolean? = null,
    var dura_ISF_weight: Double? = null,
    var smb_delivery_ratio: Double? = null,
    var smb_delivery_ratio_min: Double? = null,
    var smb_delivery_ratio_max: Double? = null,
    var smb_delivery_ratio_bg_range: Double? = null,
    var smb_max_range_extension: Double? = null,
    var enableSMB_EvenOn_OddOff: Boolean? = null,
    var enableSMB_EvenOn_OddOff_always: Boolean? = null,
    var iob_threshold_percent: Int? = null,
    var profile_percentage: Int? = null // end of AutoISF only
)