package app.aaps.pump.diaconn.di

import app.aaps.pump.diaconn.packet.AppCancelSettingPacket
import app.aaps.pump.diaconn.packet.AppCancelSettingResponsePacket
import app.aaps.pump.diaconn.packet.AppConfirmSettingPacket
import app.aaps.pump.diaconn.packet.AppConfirmSettingResponsePacket
import app.aaps.pump.diaconn.packet.BasalLimitInquirePacket
import app.aaps.pump.diaconn.packet.BasalLimitInquireResponsePacket
import app.aaps.pump.diaconn.packet.BasalPauseReportPacket
import app.aaps.pump.diaconn.packet.BasalPauseSettingPacket
import app.aaps.pump.diaconn.packet.BasalPauseSettingResponsePacket
import app.aaps.pump.diaconn.packet.BasalSettingPacket
import app.aaps.pump.diaconn.packet.BasalSettingReportPacket
import app.aaps.pump.diaconn.packet.BasalSettingResponsePacket
import app.aaps.pump.diaconn.packet.BatteryWarningReportPacket
import app.aaps.pump.diaconn.packet.BigAPSMainInfoInquirePacket
import app.aaps.pump.diaconn.packet.BigAPSMainInfoInquireResponsePacket
import app.aaps.pump.diaconn.packet.BigLogInquirePacket
import app.aaps.pump.diaconn.packet.BigLogInquireResponsePacket
import app.aaps.pump.diaconn.packet.BigMainInfoInquirePacket
import app.aaps.pump.diaconn.packet.BigMainInfoInquireResponsePacket
import app.aaps.pump.diaconn.packet.BolusSpeedInquirePacket
import app.aaps.pump.diaconn.packet.BolusSpeedInquireResponsePacket
import app.aaps.pump.diaconn.packet.BolusSpeedSettingPacket
import app.aaps.pump.diaconn.packet.BolusSpeedSettingReportPacket
import app.aaps.pump.diaconn.packet.BolusSpeedSettingResponsePacket
import app.aaps.pump.diaconn.packet.ConfirmReportPacket
import app.aaps.pump.diaconn.packet.DiaconnG8Packet
import app.aaps.pump.diaconn.packet.DisplayTimeInquirePacket
import app.aaps.pump.diaconn.packet.DisplayTimeInquireResponsePacket
import app.aaps.pump.diaconn.packet.DisplayTimeoutSettingPacket
import app.aaps.pump.diaconn.packet.DisplayTimeoutSettingResponsePacket
import app.aaps.pump.diaconn.packet.IncarnationInquirePacket
import app.aaps.pump.diaconn.packet.IncarnationInquireResponsePacket
import app.aaps.pump.diaconn.packet.InjectionBasalReportPacket
import app.aaps.pump.diaconn.packet.InjectionBasalSettingPacket
import app.aaps.pump.diaconn.packet.InjectionBasalSettingResponsePacket
import app.aaps.pump.diaconn.packet.InjectionBlockReportPacket
import app.aaps.pump.diaconn.packet.InjectionCancelSettingPacket
import app.aaps.pump.diaconn.packet.InjectionCancelSettingResponsePacket
import app.aaps.pump.diaconn.packet.InjectionExtendedBolusResultReportPacket
import app.aaps.pump.diaconn.packet.InjectionExtendedBolusSettingPacket
import app.aaps.pump.diaconn.packet.InjectionExtendedBolusSettingResponsePacket
import app.aaps.pump.diaconn.packet.InjectionProgressReportPacket
import app.aaps.pump.diaconn.packet.InjectionSnackInquirePacket
import app.aaps.pump.diaconn.packet.InjectionSnackInquireResponsePacket
import app.aaps.pump.diaconn.packet.InjectionSnackResultReportPacket
import app.aaps.pump.diaconn.packet.InjectionSnackSettingPacket
import app.aaps.pump.diaconn.packet.InjectionSnackSettingResponsePacket
import app.aaps.pump.diaconn.packet.InsulinLackReportPacket
import app.aaps.pump.diaconn.packet.LanguageInquirePacket
import app.aaps.pump.diaconn.packet.LanguageInquireResponsePacket
import app.aaps.pump.diaconn.packet.LanguageSettingPacket
import app.aaps.pump.diaconn.packet.LanguageSettingResponsePacket
import app.aaps.pump.diaconn.packet.LogStatusInquirePacket
import app.aaps.pump.diaconn.packet.LogStatusInquireResponsePacket
import app.aaps.pump.diaconn.packet.RejectReportPacket
import app.aaps.pump.diaconn.packet.SerialNumInquirePacket
import app.aaps.pump.diaconn.packet.SerialNumInquireResponsePacket
import app.aaps.pump.diaconn.packet.SnackLimitInquirePacket
import app.aaps.pump.diaconn.packet.SnackLimitInquireResponsePacket
import app.aaps.pump.diaconn.packet.SoundInquirePacket
import app.aaps.pump.diaconn.packet.SoundInquireResponsePacket
import app.aaps.pump.diaconn.packet.SoundSettingPacket
import app.aaps.pump.diaconn.packet.SoundSettingResponsePacket
import app.aaps.pump.diaconn.packet.TempBasalInquirePacket
import app.aaps.pump.diaconn.packet.TempBasalInquireResponsePacket
import app.aaps.pump.diaconn.packet.TempBasalReportPacket
import app.aaps.pump.diaconn.packet.TempBasalSettingPacket
import app.aaps.pump.diaconn.packet.TempBasalSettingResponsePacket
import app.aaps.pump.diaconn.packet.TimeInquirePacket
import app.aaps.pump.diaconn.packet.TimeInquireResponsePacket
import app.aaps.pump.diaconn.packet.TimeReportPacket
import app.aaps.pump.diaconn.packet.TimeSettingPacket
import app.aaps.pump.diaconn.packet.TimeSettingResponsePacket
import dagger.Module
import dagger.android.ContributesAndroidInjector
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent

@Module
@InstallIn(SingletonComponent::class)
@Suppress("unused", "SpellCheckingInspection")
interface DiaconnG8PacketModule {
}
