package app.aaps.pump.insight.descriptors

import app.aaps.pump.insight.exceptions.app_layer_errors.AppLayerErrorException
import com.google.common.truth.Truth.assertThat
import java.lang.reflect.Modifier
import org.junit.jupiter.api.Test

/**
 * Covers [AppErrors.Companion]: the table that turns an error code from the pump into the exception
 * class raised for it.
 *
 * `AppLayerMessage` does not construct these classes normally. It does
 * `it.getConstructor(Int::class.javaPrimitiveType).newInstance(error)`, so a mapped class without a
 * public single-int constructor compiles, passes every other test, and then throws
 * `NoSuchMethodException` instead of the intended error - but only on the day the pump actually
 * reports that code. The ids are read back by reflection rather than typed out again here, so these
 * tests check that the table holds together instead of restating it.
 */
class AppErrorsTest {

    /** Every `const val` error id declared on [AppErrors], as (name, id). */
    private val errorIds: List<Pair<String, Int>> =
        AppErrors::class.java.declaredFields
            // `$stable` is generated by the Compose compiler, not an error id, so names with a `$`
            // in them are left out.
            .filter {
                Modifier.isStatic(it.modifiers) && Modifier.isFinal(it.modifiers) &&
                    it.type == Int::class.javaPrimitiveType && !it.name.contains('$')
            }
            .map { field ->
                field.isAccessible = true
                field.name to field.getInt(null)
            }

    @Test
    fun theTestFindsTheErrorIds() {
        // Guards the reflection above: if it ever returns nothing, every other test here would pass
        // without checking anything at all.
        assertThat(errorIds.size).isAtLeast(50)
    }

    @Test
    fun everyDeclaredIdIsMappedToAnException() {
        val unmapped = errorIds.filter { (_, id) -> AppErrors.fromId(id) == null }
        assertThat(unmapped.map { it.first }).isEmpty()
    }

    /** Two codes sharing an id would leave one of them unreachable. */
    @Test
    fun theIdsAreAllDifferent() {
        val ids = errorIds.map { it.second }
        assertThat(ids.toSet()).hasSize(ids.size)
    }

    @Test
    fun everyMappedExceptionCanBeBuiltTheWayTheParserBuildsIt() {
        val broken = errorIds.mapNotNull { (name, id) ->
            val type = AppErrors.fromId(id) ?: return@mapNotNull name
            runCatching { type.getConstructor(Int::class.javaPrimitiveType).newInstance(id) }
                .fold(onSuccess = { null }, onFailure = { name })
        }
        assertThat(broken).isEmpty()
    }

    @Test
    fun everyMappedExceptionIsAnAppLayerError() {
        val wrongType = errorIds.filter { (_, id) ->
            val type = AppErrors.fromId(id)
            type != null && !AppLayerErrorException::class.java.isAssignableFrom(type)
        }
        assertThat(wrongType.map { it.first }).isEmpty()
    }

    @Test
    fun fromId_returnsNullForACodeThePumpNeverSends() {
        assertThat(AppErrors.fromId(0)).isNull()
        assertThat(AppErrors.fromId(-1)).isNull()
        assertThat(AppErrors.fromId(Int.MAX_VALUE)).isNull()
    }
}
